<?php

namespace Database\Seeders;

use App\Models\SubscriptionPlan;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class SubscriptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Free Plan
        SubscriptionPlan::create([
            'uuid' => (string) Str::uuid(),
            'name' => 'free',
            'display_name' => 'Free Plan',
            'description' => 'Basic features for individual users',
            'plan_type' => 'free',
            'price_per_month' => 0,
            'price_per_semester' => 0,
            'price_per_year' => 0,
            'billing_cycle' => 'monthly',
            'available_billing_cycles' => ['monthly'],
            'trial_days' => 0,
            'has_trial' => false,
            'features' => [
                'basic_course_access',
                'basic_discussions',
                'limited_storage',
            ],
            'limits' => [
                'max_courses' => 3,
                'max_storage_gb' => 5,
                'max_file_upload_size_mb' => 10,
            ],
            'max_courses' => 3,
            'max_storage_gb' => 5,
            'max_file_upload_size_mb' => 10,
            'allow_group_submissions' => false,
            'allow_rubrics' => false,
            'allow_attendance_tracking' => false,
            'allow_document_generation' => false,
            'allow_api_access' => false,
            'allow_white_label' => false,
            'is_recommended' => false,
            'can_upgrade' => true,
            'can_downgrade' => false,
            'is_active' => true,
            'sort_order' => 10,
        ]);

        // Basic Plan
        SubscriptionPlan::create([
            'uuid' => (string) Str::uuid(),
            'name' => 'basic',
            'display_name' => 'Basic Plan',
            'description' => 'Perfect for individual students and learners',
            'plan_type' => 'b2c',
            'price_per_month' => 9.99,
            'price_per_semester' => 35.99,
            'price_per_year' => 99.99,
            'billing_cycle' => 'monthly',
            'available_billing_cycles' => ['monthly', 'semester', 'yearly'],
            'trial_days' => 14,
            'has_trial' => true,
            'features' => [
                'full_course_access',
                'discussions',
                'group_submissions',
                'rubrics',
                'attendance_tracking',
                '5gb_storage',
            ],
            'limits' => [
                'max_courses' => 10,
                'max_storage_gb' => 5,
                'max_file_upload_size_mb' => 50,
            ],
            'max_courses' => 10,
            'max_storage_gb' => 5,
            'max_file_upload_size_mb' => 50,
            'allow_group_submissions' => true,
            'allow_rubrics' => true,
            'allow_attendance_tracking' => true,
            'allow_document_generation' => false,
            'allow_api_access' => false,
            'allow_white_label' => false,
            'is_recommended' => true,
            'can_upgrade' => true,
            'can_downgrade' => true,
            'prorated_upgrades' => true,
            'cancellation_minimum_days' => 7,
            'is_active' => true,
            'sort_order' => 20,
        ]);

        // Pro Plan
        SubscriptionPlan::create([
            'uuid' => (string) Str::uuid(),
            'name' => 'pro',
            'display_name' => 'Pro Plan',
            'description' => 'Advanced features for serious learners and educators',
            'plan_type' => 'b2c',
            'price_per_month' => 19.99,
            'price_per_semester' => 69.99,
            'price_per_year' => 199.99,
            'billing_cycle' => 'monthly',
            'available_billing_cycles' => ['monthly', 'semester', 'yearly'],
            'trial_days' => 14,
            'has_trial' => true,
            'features' => [
                'full_course_access',
                'advanced_discussions',
                'group_submissions',
                'rubrics',
                'attendance_tracking',
                'document_generation',
                'api_access',
                '25gb_storage',
                'priority_support',
            ],
            'limits' => [
                'max_courses' => 50,
                'max_storage_gb' => 25,
                'max_file_upload_size_mb' => 100,
            ],
            'max_courses' => 50,
            'max_storage_gb' => 25,
            'max_file_upload_size_mb' => 100,
            'allow_group_submissions' => true,
            'allow_rubrics' => true,
            'allow_attendance_tracking' => true,
            'allow_document_generation' => true,
            'allow_api_access' => true,
            'allow_white_label' => false,
            'max_administrators' => 2,
            'is_recommended' => false,
            'can_upgrade' => true,
            'can_downgrade' => true,
            'prorated_upgrades' => true,
            'cancellation_minimum_days' => 7,
            'refundable' => true,
            'refund_period_days' => 30,
            'is_active' => true,
            'sort_order' => 30,
        ]);

        // Department Plan (B2B)
        SubscriptionPlan::create([
            'uuid' => (string) Str::uuid(),
            'name' => 'department',
            'display_name' => 'Department Plan',
            'description' => 'For academic departments with multiple faculty and courses',
            'plan_type' => 'b2b',
            'price_per_month' => 99.99,
            'price_per_semester' => 349.99,
            'price_per_year' => 999.99,
            'billing_cycle' => 'monthly',
            'available_billing_cycles' => ['monthly', 'semester', 'yearly'],
            'trial_days' => 30,
            'has_trial' => true,
            'features' => [
                'unlimited_courses',
                'unlimited_students',
                'department_analytics',
                'priority_support',
                'dedicated_manager',
                'sso_enabled',
                'custom_branding',
                'api_access',
                '100gb_storage',
            ],
            'limits' => [
                'max_courses' => null,
                'max_storage_gb' => 100,
                'max_file_upload_size_mb' => 500,
            ],
            'max_courses' => null,
            'max_storage_gb' => 100,
            'max_file_upload_size_mb' => 500,
            'allow_group_submissions' => true,
            'allow_rubrics' => true,
            'allow_attendance_tracking' => true,
            'allow_document_generation' => true,
            'allow_api_access' => true,
            'allow_white_label' => true,
            'max_administrators' => 10,
            'min_seats' => 5,
            'max_seats' => 100,
            'priority_support' => true,
            'dedicated_account_manager' => true,
            'sso_enabled' => true,
            'api_access' => true,
            'custom_branding' => true,
            'is_recommended' => false,
            'can_upgrade' => true,
            'can_downgrade' => true,
            'prorated_upgrades' => true,
            'cancellation_minimum_days' => 30,
            'refundable' => true,
            'refund_period_days' => 30,
            'is_active' => true,
            'sort_order' => 40,
        ]);

        // University Plan (B2B)
        SubscriptionPlan::create([
            'uuid' => (string) Str::uuid(),
            'name' => 'university',
            'display_name' => 'University Plan',
            'description' => 'Complete solution for entire universities',
            'plan_type' => 'b2b',
            'price_per_month' => 499.99,
            'price_per_semester' => 1749.99,
            'price_per_year' => 4999.99,
            'billing_cycle' => 'monthly',
            'available_billing_cycles' => ['monthly', 'semester', 'yearly'],
            'trial_days' => 60,
            'has_trial' => true,
            'features' => [
                'unlimited_everything',
                'white_label',
                'custom_integrations',
                '24_7_support',
                'dedicated_infrastructure',
                'advanced_analytics',
                'custom_reporting',
                'api_access',
                'unlimited_storage',
            ],
            'limits' => [
                'max_courses' => null,
                'max_storage_gb' => null,
                'max_file_upload_size_mb' => 1000,
            ],
            'max_courses' => null,
            'max_storage_gb' => null,
            'max_file_upload_size_mb' => 1000,
            'allow_group_submissions' => true,
            'allow_rubrics' => true,
            'allow_attendance_tracking' => true,
            'allow_document_generation' => true,
            'allow_api_access' => true,
            'allow_white_label' => true,
            'max_administrators' => null,
            'min_seats' => 50,
            'max_seats' => null,
            'priority_support' => true,
            'dedicated_account_manager' => true,
            'sso_enabled' => true,
            'api_access' => true,
            'custom_branding' => true,
            'is_recommended' => false,
            'can_upgrade' => true,
            'can_downgrade' => true,
            'prorated_upgrades' => true,
            'cancellation_minimum_days' => 60,
            'refundable' => true,
            'refund_period_days' => 60,
            'is_active' => true,
            'sort_order' => 50,
        ]);
    }
}
