@extends('layouts.app')
@section('title','Creator Wallet')
@section('page-title','Creator Wallet')
@section('page-subtitle','Auditable earnings, payouts and withdrawals')
@section('content')
<div class="grid gap-4 md:grid-cols-3"><div class="rounded-2xl border bg-white p-5"><p class="text-sm text-slate-500">Available</p><p class="mt-2 text-3xl font-semibold">{{ $wallet->currency }} {{ number_format((float)$wallet->available_balance,2) }}</p></div><div class="rounded-2xl border bg-white p-5"><p class="text-sm text-slate-500">Pending</p><p class="mt-2 text-3xl font-semibold">{{ number_format((float)$wallet->pending_balance,2) }}</p></div><div class="rounded-2xl border bg-white p-5"><p class="text-sm text-slate-500">Lifetime</p><p class="mt-2 text-3xl font-semibold">{{ number_format((float)$wallet->lifetime_earnings,2) }}</p></div></div>
<div class="mt-6 grid gap-6 lg:grid-cols-2"><form method="POST" action="{{ route('commerce.payout-accounts.store') }}" class="grid gap-3 rounded-2xl border bg-white p-5">@csrf<h2 class="font-semibold">Payout account</h2><select name="provider" class="rounded-xl border-slate-300"><option>bank</option><option>paystack</option><option>manual</option></select><input required name="account_name" class="rounded-xl border-slate-300" placeholder="Account name"><input required name="account_number" class="rounded-xl border-slate-300" placeholder="Account number"><input name="bank_name" class="rounded-xl border-slate-300" placeholder="Bank name"><input name="bank_code" class="rounded-xl border-slate-300" placeholder="Bank code"><input required name="currency" value="{{ $wallet->currency }}" class="rounded-xl border-slate-300"><button class="rounded-xl border px-4 py-2">Save securely</button></form><form method="POST" action="{{ route('commerce.withdrawals.store') }}" class="grid gap-3 rounded-2xl border bg-white p-5">@csrf<h2 class="font-semibold">Request withdrawal</h2><select required name="payout_account_id" class="rounded-xl border-slate-300">@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->bank_name }} · {{ $account->masked_account_number }} @if(!$account->is_verified)(unverified)@endif</option>@endforeach</select><input required type="number" step="0.01" name="amount" class="rounded-xl border-slate-300" placeholder="Amount"><button class="rounded-xl bg-blue-600 px-4 py-2 text-white">Request withdrawal</button></form></div>
<div class="mt-6 rounded-2xl border bg-white p-5"><h2 class="font-semibold">Ledger</h2>@foreach($wallet->entries as $entry)<div class="flex justify-between border-t py-3 text-sm"><span>{{ $entry->description }}</span><span>{{ $entry->direction==='credit'?'+':'-' }}{{ number_format((float)$entry->amount,2) }}</span></div>@endforeach</div><div class="mt-6 rounded-2xl border bg-white p-5"><h2 class="font-semibold">Revenue allocations</h2>@foreach($allocations as $allocation)<div class="flex justify-between border-t py-3 text-sm"><span>{{ $allocation->allocation_type }} · {{ $allocation->status }}</span><span>{{ number_format((float)$allocation->amount,2) }}</span></div>@endforeach{{ $allocations->links() }}</div>
@endsection
