@extends('layouts.app')
@section('title','Creator Profile')
@section('page-title','Creator Profile')
@section('page-subtitle','Public identity, expertise, privacy and verification')
@section('content')
@include('knowledge._nav')
<div class="grid gap-6 lg:grid-cols-2"><form method="POST" action="{{ route('knowledge.creator.update') }}" class="space-y-4 rounded-2xl border bg-white p-6">@csrf @method('PUT')
@foreach(['headline'=>'Headline','position'=>'Academic position','orcid'=>'ORCID','website'=>'Website'] as $name=>$label)<label class="block text-sm font-medium">{{ $label }}<input class="mt-1 w-full rounded-xl border-slate-300" name="{{ $name }}" value="{{ old($name,$profile?->{$name}) }}"></label>@endforeach
<label class="block text-sm font-medium">Biography<textarea class="mt-1 w-full rounded-xl border-slate-300" rows="6" name="biography">{{ old('biography',$profile?->biography) }}</textarea></label><label class="block text-sm font-medium">Expertise (comma separated)<input class="mt-1 w-full rounded-xl border-slate-300" name="expertise" value="{{ old('expertise',implode(', ',$profile?->expertise ?? [])) }}"></label>
<div class="grid gap-2 text-sm">@foreach(['is_public'=>'Public profile','show_institution'=>'Show institution','show_department'=>'Show department','show_impact'=>'Show impact metrics','personalized_recommendations'=>'Use private activity for recommendations'] as $name=>$label)<label><input type="checkbox" name="{{ $name }}" value="1" @checked(old($name,$name==='is_public' ? ($profile?->is_public ?? true) : data_get($profile?->privacy_settings,$name,false)))> {{ $label }}</label>@endforeach</div><button class="rounded-xl bg-blue-600 px-5 py-2.5 text-white">Save profile</button></form>
<div class="rounded-2xl border bg-white p-6"><h2 class="text-xl font-semibold">ORCID synchronization</h2><p class="mt-2 text-sm text-slate-600">Import public identity and work metadata from the ORCID saved above. AcadFlow stores source provenance and never imports private records.</p><form method="POST" action="{{ route('knowledge.creator.orcid.sync') }}" class="mt-4">@csrf<button class="rounded-xl border px-4 py-2 text-sm">Synchronize saved ORCID record</button></form></div>
<form method="POST" action="{{ route('knowledge.verification.store') }}" class="space-y-4 rounded-2xl border bg-white p-6">@csrf<h2 class="text-xl font-semibold">Request verification</h2><select name="verification_type" class="w-full rounded-xl border-slate-300">@foreach(['lecturer','professor','researcher','student_ambassador','department','faculty','university','organization','institution_partner'] as $type)<option value="{{ $type }}">{{ ucwords(str_replace('_',' ',$type)) }}</option>@endforeach</select><textarea name="statement" rows="6" class="w-full rounded-xl border-slate-300" placeholder="Explain the role and evidence administrators should review"></textarea><button class="rounded-xl border border-blue-600 px-5 py-2.5 font-semibold text-blue-700">Submit for human review</button></form></div>
@endsection
