@extends('layouts.app')
@section('title',$creator->full_name)
@section('page-title',$creator->full_name)
@section('page-subtitle',$creator->creatorProfile?->headline ?? 'Academic creator')
@section('content')
@include('knowledge._nav')
<div class="space-y-7">
    <section class="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-slate-950 via-indigo-950 to-cyan-950 p-7 text-white shadow-xl sm:p-9"><div class="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-cyan-400/15 blur-3xl"></div><div class="relative flex flex-col gap-6 md:flex-row md:items-center"><div class="flex h-20 w-20 shrink-0 items-center justify-center rounded-[1.5rem] bg-white text-3xl font-black text-indigo-700 shadow-lg">{{ strtoupper(substr($creator->first_name ?: $creator->full_name,0,1)) }}</div><div><p class="text-xs font-black uppercase tracking-[.2em] text-cyan-300">Academic creator</p><h1 class="mt-1 text-3xl font-black sm:text-4xl">{{ $creator->full_name }}</h1><p class="mt-2 text-sm text-slate-300">{{ $creator->creatorProfile?->headline ?: ($creator->creatorProfile?->position ?: 'Contributor to the AcadFlow knowledge ecosystem') }}</p></div></div></section>
    <div class="grid gap-6 lg:grid-cols-[320px_1fr]"><aside class="space-y-5"><section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="font-black text-slate-900">About</h2><p class="mt-3 text-sm leading-7 text-slate-600">{{ $creator->creatorProfile?->biography ?: 'No public biography has been added yet.' }}</p><dl class="mt-5 space-y-4 text-sm"><div><dt class="text-xs font-bold uppercase text-slate-400">Position</dt><dd class="mt-1 font-semibold text-slate-800">{{ $creator->creatorProfile?->position ?: 'Not specified' }}</dd></div>@if($creator->creatorProfile?->orcid)<div><dt class="text-xs font-bold uppercase text-slate-400">ORCID</dt><dd class="mt-1 break-all font-semibold text-slate-800">{{ $creator->creatorProfile->orcid }}</dd></div>@endif</dl></section><section class="rounded-3xl border border-indigo-200 bg-indigo-50 p-6"><p class="text-xs font-black uppercase tracking-wide text-indigo-600">Reputation</p><p class="mt-2 text-4xl font-black text-indigo-800">{{ number_format((float)($creator->reputationProfile?->overall_score ?? 0),1) }}</p><p class="mt-1 text-sm font-bold text-indigo-700">{{ str($creator->reputationProfile?->level_key ?? 'new_contributor')->replace('_',' ')->headline() }}</p></section></aside><main><div class="flex items-end justify-between"><div><p class="text-xs font-black uppercase tracking-[.18em] text-indigo-600">Published work</p><h2 class="mt-1 text-2xl font-black text-slate-900">Publications</h2></div></div><div class="mt-5 grid gap-5 md:grid-cols-2">@forelse($publications as $publication)<a href="{{ route('knowledge.show',$publication) }}" class="group rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-indigo-200 hover:shadow-xl"><span class="rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-700">{{ str($publication->content_type)->replace('_',' ')->headline() }}</span><h3 class="mt-4 text-lg font-black text-slate-900 group-hover:text-indigo-700">{{ $publication->title }}</h3><p class="mt-3 text-sm leading-6 text-slate-500">{{ Illuminate\Support\Str::limit($publication->excerpt,140) }}</p><p class="mt-5 text-sm font-black text-indigo-600">Open publication →</p></a>@empty<div class="md:col-span-2 rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center text-sm text-slate-500">No public publications yet.</div>@endforelse</div><div class="mt-5">{{ $publications->links() }}</div></main></div>
</div>
@endsection
