@extends('layouts.app')
@php($editing = $publication->exists)
@section('title', $editing ? 'Edit Publication' : 'Create Publication')
@section('page-title', $editing ? 'Edit publication' : 'Create publication')
@section('page-subtitle', $editing ? ucwords(str_replace('_',' ',$publication->status)) : 'Use the shared versioned content workspace')
@section('content')
<div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]">
<form id="publication-main-form" method="POST" action="{{ $editing ? route('knowledge.manage.update',$publication) : route('knowledge.manage.store') }}" class="space-y-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">@csrf @if($editing) @method('PUT') @endif
    @if($editing && $publication->sourceResearchProject)<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900">Linked to approved research: <strong>{{ $publication->sourceResearchProject->title }}</strong>. The source relationship is permanent.</div>@endif
    <label class="block"><span class="text-sm font-medium">Title</span><input name="title" required maxlength="255" value="{{ old('title',$publication->title) }}" class="mt-2 w-full rounded-xl border-slate-300"></label>
    <label class="block"><span class="text-sm font-medium">Excerpt</span><textarea name="excerpt" rows="3" class="mt-2 w-full rounded-xl border-slate-300">{{ old('excerpt',$publication->excerpt) }}</textarea></label>
    <label class="block"><span class="text-sm font-medium">Content</span><textarea name="body" required rows="24" data-rich-editor data-editor-height="460px" data-ai-url="{{ route('ai.writing') }}" data-ai-enabled="{{ \App\Services\SettingService::get('ai_editor_suggestions_enabled', true) ? '1' : '0' }}" data-ai-min-chars="{{ \App\Services\SettingService::get('ai_editor_suggestion_min_chars', 60) }}" data-ai-delay="{{ \App\Services\SettingService::get('ai_editor_suggestion_delay_ms', 1600) }}" class="mt-2 w-full rounded-xl border-slate-300 font-serif leading-7" placeholder="Write your publication content…">{{ old('body',$publication->document?->body) }}</textarea><span class="mt-1 block text-xs text-slate-500">Every save creates a recoverable content version. The editor supports headings, formatting, lists, alignment, links, code, and reviewable AI writing suggestions.</span></label>
    <div class="flex justify-end"><button class="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white">Save publication</button></div>
</form>
<aside class="space-y-5">
    <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-semibold">Publishing settings</h3><div class="mt-4 space-y-4">
        <label class="block"><span class="text-sm font-medium">Content type</span><select name="content_type" form="publication-main-form" class="mt-2 w-full rounded-xl border-slate-300">@foreach(['academic_article','research_output','study_guide','tutorial','case_study','career_guide','digital_resource'] as $type)<option value="{{ $type }}" @selected(old('content_type',$publication->content_type ?: 'academic_article')===$type)>{{ ucwords(str_replace('_',' ',$type)) }}</option>@endforeach</select></label>
        <label class="block"><span class="text-sm font-medium">Category</span><select name="category_id" form="publication-main-form" class="mt-2 w-full rounded-xl border-slate-300"><option value="">No category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id',$publication->category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select></label>
        <label class="block"><span class="text-sm font-medium">Tags</span><input name="tags" form="publication-main-form" value="{{ old('tags',$editing ? $publication->tags->pluck('name')->implode(', ') : '') }}" class="mt-2 w-full rounded-xl border-slate-300" placeholder="research, education"></label>
        <label class="block"><span class="text-sm font-medium">Visibility</span><select name="visibility" form="publication-main-form" class="mt-2 w-full rounded-xl border-slate-300"><option value="institution" @selected(old('visibility',$publication->visibility ?: 'institution')==='institution')>Institution</option><option value="public" @selected(old('visibility',$publication->visibility)==='public')>Public</option></select></label>
        <label class="block"><span class="text-sm font-medium">Access</span><select name="access_type" form="publication-main-form" class="mt-2 w-full rounded-xl border-slate-300"><option value="free" @selected(old('access_type',$publication->access_type ?: 'free')==='free')>Free</option><option value="institution" @selected(old('access_type',$publication->access_type)==='institution')>Institution entitlement</option><option value="premium" @selected(old('access_type',$publication->access_type)==='premium')>Premium</option></select></label>
        <label class="block"><span class="text-sm font-medium">Price</span><input type="number" min="0" step="0.01" name="price" form="publication-main-form" value="{{ old('price',$publication->price ?? 0) }}" class="mt-2 w-full rounded-xl border-slate-300"></label>
    </div></div>
    @if($editing)
    <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-semibold">Workflow</h3><p class="mt-2 text-sm text-slate-500">Status: {{ ucwords(str_replace('_',' ',$publication->status)) }}</p>@if($publication->moderation_note)<p class="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{{ $publication->moderation_note }}</p>@endif
        @can('submit',$publication) <form method="POST" action="{{ route('knowledge.manage.submit',$publication) }}" class="mt-4">@csrf<button class="w-full rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Submit for moderation</button></form> @endcan
        @can('moderate',$publication)<form method="POST" action="{{ route('knowledge.manage.moderate',$publication) }}" class="mt-4 space-y-3">@csrf<select name="decision" class="w-full rounded-xl border-slate-300 text-sm"><option value="approve">Approve and publish</option><option value="request_changes">Request changes</option><option value="reject">Reject</option><option value="unpublish">Unpublish</option></select><textarea name="note" rows="3" class="w-full rounded-xl border-slate-300 text-sm" placeholder="Moderation reason"></textarea><button class="w-full rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white">Record decision</button></form>@endcan
    </div>
    @endif
</aside>
</div>
@endsection
