@extends('layouts.app')
@section('title','Academic Reputation')
@section('page-title','Academic Reputation')
@section('page-subtitle','Quality, research impact and meaningful contribution—not raw popularity')
@section('content')
@include('knowledge._nav')
<div class="space-y-7">
    <section class="rounded-[2rem] bg-gradient-to-br from-amber-950 via-slate-950 to-indigo-950 p-7 text-white shadow-xl sm:p-9"><p class="text-xs font-black uppercase tracking-[.24em] text-amber-300">Academic reputation</p><h1 class="mt-2 text-3xl font-black sm:text-4xl">Contributor leaderboard</h1><p class="mt-3 max-w-3xl text-sm leading-7 text-slate-300">A reputation view focused on verified scholarly contribution, publication quality and citation impact.</p></section>
    <div class="grid gap-4 md:grid-cols-3">@foreach($profiles->take(3) as $profile)<a href="{{ route('knowledge.creator',$profile->user) }}" class="rounded-3xl border {{ $loop->first?'border-amber-200 bg-amber-50':'border-slate-200 bg-white' }} p-6 text-center shadow-sm"><div class="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl {{ $loop->first?'bg-amber-400 text-slate-950':'bg-slate-900 text-white' }} text-xl font-black">#{{ $profiles->firstItem()+$loop->index }}</div><h2 class="mt-4 font-black text-slate-900">{{ $profile->user?->full_name }}</h2><p class="mt-1 text-xs font-bold uppercase tracking-wide text-slate-400">{{ str($profile->level_key)->replace('_',' ')->headline() }}</p><p class="mt-4 text-3xl font-black text-indigo-700">{{ number_format((float)$profile->overall_score,1) }}</p><p class="text-xs text-slate-400">reputation score</p></a>@endforeach</div>
    <section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-6 py-5"><h2 class="text-xl font-black text-slate-900">All ranked creators</h2></div><div class="overflow-x-auto"><table class="min-w-full"><thead class="bg-slate-50 text-left text-[11px] font-black uppercase tracking-wider text-slate-400"><tr><th class="px-6 py-3">Rank</th><th class="px-6 py-3">Creator</th><th class="px-6 py-3">Level</th><th class="px-6 py-3">Score</th><th class="px-6 py-3">Publications</th><th class="px-6 py-3">Citations</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($profiles as $profile)<tr class="hover:bg-slate-50"><td class="px-6 py-4 text-lg font-black text-slate-500">#{{ $profiles->firstItem()+$loop->index }}</td><td class="px-6 py-4"><a class="font-black text-indigo-700 hover:underline" href="{{ route('knowledge.creator',$profile->user) }}">{{ $profile->user?->full_name }}</a></td><td class="px-6 py-4 text-sm font-semibold text-slate-600">{{ str($profile->level_key)->replace('_',' ')->headline() }}</td><td class="px-6 py-4 font-black text-slate-900">{{ number_format((float)$profile->overall_score,1) }}</td><td class="px-6 py-4 text-sm text-slate-600">{{ $profile->publication_count }}</td><td class="px-6 py-4 text-sm text-slate-600">{{ $profile->citation_count }}</td></tr>@empty<tr><td colspan="6" class="px-6 py-12 text-center text-sm text-slate-500">No reputation profiles are available yet.</td></tr>@endforelse</tbody></table></div></section>
    {{ $profiles->links() }}
</div>
@endsection
