@extends('layouts.app')
@section('title','Reading Lists')
@section('page-title','Reading Lists')
@section('page-subtitle','Curated academic collections for reading, research and collaboration')
@section('content')
@include('knowledge._nav')
<div class="space-y-7">
    <section class="rounded-[2rem] bg-gradient-to-br from-cyan-950 via-slate-950 to-indigo-950 p-7 text-white shadow-xl sm:p-9"><p class="text-xs font-black uppercase tracking-[.24em] text-cyan-300">Curated knowledge</p><h1 class="mt-2 text-3xl font-black sm:text-4xl">Reading lists</h1><p class="mt-3 max-w-3xl text-sm leading-7 text-slate-300">Organize publications into personal, course, research, departmental or collaborative collections and track your reading progress.</p></section>
    @auth<details class="rounded-3xl border border-slate-200 bg-white shadow-sm"><summary class="cursor-pointer list-none p-5 text-lg font-black text-slate-900">+ Create a reading list</summary><form method="POST" action="{{ route('knowledge.reading.store') }}" class="grid gap-3 border-t border-slate-100 p-5 md:grid-cols-2">@csrf<input required name="title" class="rounded-xl border-slate-300" placeholder="List title"><input name="description" class="rounded-xl border-slate-300" placeholder="Description"><select name="list_type" class="rounded-xl border-slate-300">@foreach(['private','public','course','research','department','collaborative'] as $type)<option>{{ $type }}</option>@endforeach</select><select name="visibility" class="rounded-xl border-slate-300"><option>private</option><option>public</option><option>institution</option></select><label class="flex items-center gap-2 rounded-xl bg-slate-50 px-4 py-3 text-sm font-bold"><input type="checkbox" name="is_collaborative" value="1"> Collaborative list</label><button class="rounded-xl bg-cyan-700 px-4 py-2 text-sm font-black text-white">Create list</button></form></details>@endauth
    <div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">@forelse($lists as $list)<a href="{{ route('knowledge.reading.show',$list) }}" class="group flex min-h-56 flex-col rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-cyan-200 hover:shadow-xl"><div class="flex items-center justify-between"><span class="rounded-full bg-cyan-50 px-3 py-1 text-xs font-bold text-cyan-700">{{ str($list->list_type)->headline() }}</span><span class="text-xs font-bold text-slate-400">{{ $list->items_count }} items</span></div><h2 class="mt-5 text-xl font-black text-slate-900 group-hover:text-cyan-700">{{ $list->title }}</h2><p class="mt-3 line-clamp-3 text-sm leading-6 text-slate-500">{{ $list->description }}</p><div class="mt-auto border-t border-slate-100 pt-5 text-sm font-black text-cyan-700">Open collection →</div></a>@empty<div class="md:col-span-2 xl:col-span-3 rounded-[2rem] border border-dashed border-slate-300 bg-white p-14 text-center"><h2 class="text-xl font-black text-slate-900">No reading lists yet</h2><p class="mt-2 text-sm text-slate-500">Create a collection to start organizing academic reading.</p></div>@endforelse</div>{{ $lists->links() }}
</div>
@endsection
