@extends('layouts.app')
@section('title',$list->title)
@section('page-title',$list->title)
@section('page-subtitle',$list->list_type.' reading list')
@section('content')
@include('knowledge._nav')
<div class="space-y-6">
    <section class="rounded-[2rem] bg-gradient-to-br from-slate-950 via-cyan-950 to-indigo-950 p-7 text-white shadow-xl sm:p-9"><div class="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div class="max-w-4xl"><div class="flex flex-wrap gap-2"><span class="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">{{ str($list->list_type)->headline() }}</span><span class="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">{{ str($list->visibility)->headline() }}</span><span class="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">{{ $list->items->count() }} items</span></div><h1 class="mt-4 text-3xl font-black sm:text-4xl">{{ $list->title }}</h1><p class="mt-3 text-sm leading-7 text-slate-300">{{ $list->description }}</p><p class="mt-3 text-xs text-cyan-200">Owner: {{ $list->owner?->full_name }} @if($list->researchProject)· Linked to {{ $list->researchProject->title }}@endif</p></div><div class="flex gap-2"><a href="{{ route('knowledge.reading.export',['list'=>$list,'format'=>'csv']) }}" class="rounded-xl bg-white px-4 py-2 text-sm font-black text-slate-950">CSV</a><a href="{{ route('knowledge.reading.export',['list'=>$list,'format'=>'json']) }}" class="rounded-xl border border-white/20 bg-white/10 px-4 py-2 text-sm font-black">JSON</a></div></div></section>
    <div class="grid gap-6 xl:grid-cols-[minmax(0,2fr)_340px]"><main class="space-y-5">
        @auth<form method="POST" action="{{ route('knowledge.reading.items.store',$list) }}" class="flex flex-col gap-3 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row">@csrf<input name="publication_id" required type="number" class="rounded-xl border-slate-300 sm:w-48" placeholder="Publication ID"><input name="note" class="min-w-0 flex-1 rounded-xl border-slate-300" placeholder="Why is this useful?"><button class="rounded-xl bg-cyan-700 px-5 py-2.5 text-sm font-black text-white">Add publication</button></form>@endauth
        <section class="space-y-4">@forelse($list->items as $item)<article class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h2 class="font-black text-slate-900">{{ $item->item?->title ?? class_basename($item->item_type) }}</h2>@if($item->note)<p class="mt-2 text-sm leading-6 text-slate-500">{{ $item->note }}</p>@endif</div>@auth<form method="POST" action="{{ route('knowledge.reading.items.update',[$list,$item]) }}" class="flex gap-2">@csrf @method('PATCH')<select name="status" class="rounded-xl border-slate-300 text-sm"><option @selected($item->status==='unread')>unread</option><option @selected($item->status==='reading')>reading</option><option @selected($item->status==='completed')>completed</option></select><button class="rounded-xl bg-slate-900 px-3 py-2 text-xs font-black text-white">Update</button></form>@endauth</div></article>@empty<div class="rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center text-sm text-slate-500">This list is empty.</div>@endforelse</section>
    </main><aside>@if(auth()->id()===$list->owner_id || auth()->user()?->isAdmin())<section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-black text-slate-900">Collaborators</h2><p class="mt-1 text-xs leading-5 text-slate-500">Give another user view or edit access to this collection.</p><form method="POST" action="{{ route('knowledge.reading.members.store',$list) }}" class="mt-4 space-y-3">@csrf<input required type="number" name="user_id" class="w-full rounded-xl border-slate-300" placeholder="User ID"><select name="role" class="w-full rounded-xl border-slate-300"><option>viewer</option><option>editor</option></select><button class="w-full rounded-xl bg-cyan-700 px-4 py-2 text-sm font-black text-white">Add collaborator</button></form></section>@endif</aside></div>
</div>
@endsection
