@extends('layouts.app')
@php($editing=isset($challenge))
@section('title',$editing?'Edit Challenge':'Create Challenge')
@section('page-title',$editing?'Edit Challenge':'Create Challenge')
@section('page-subtitle','Configure eligibility, teams, deadlines, judges, criteria and rewards')
@section('content')
@include('knowledge._nav')
<form method="POST" enctype="multipart/form-data" action="{{ $editing?route('knowledge.challenges.update',$challenge):route('knowledge.challenges.store') }}" class="mx-auto max-w-5xl space-y-6 rounded-2xl border bg-white p-6">@csrf @if($editing)@method('PUT')@endif
<div><label class="font-medium">Challenge title</label><input name="title" required value="{{ old('title',$challenge->title??'') }}" class="mt-1 w-full rounded-xl border-slate-300"></div><div><label class="font-medium">Challenge cover image</label><input type="file" name="cover_image" accept="image/jpeg,image/png,image/webp" class="mt-1 w-full rounded-xl border border-slate-300 p-2"><p class="mt-1 text-xs text-slate-500">JPG, PNG or WebP, up to 8 MB. Existing covers remain unless replaced.</p></div>
<div><label class="font-medium">Description</label><textarea name="description" required rows="6" class="mt-1 w-full rounded-xl border-slate-300">{{ old('description',$challenge->description??'') }}</textarea></div>
<div class="grid gap-4 md:grid-cols-4"><div><label class="font-medium">Type</label><select name="challenge_type" class="mt-1 w-full rounded-xl border-slate-300">@foreach(['writing','research','tutorial','project_documentation','innovation','siwes_report'] as $type)<option value="{{ $type }}" @selected(old('challenge_type',$challenge->challenge_type??'research')===$type)>{{ str($type)->headline() }}</option>@endforeach</select></div><div><label class="font-medium">Participation</label><select name="participation_mode" class="mt-1 w-full rounded-xl border-slate-300">@foreach(['individual','team','both'] as $value)<option @selected(old('participation_mode',$challenge->participation_mode??'individual')===$value)>{{ $value }}</option>@endforeach</select></div><div><label class="font-medium">Visibility</label><select name="visibility" class="mt-1 w-full rounded-xl border-slate-300">@foreach(['public','institution','private'] as $value)<option @selected(old('visibility',$challenge->visibility??'public')===$value)>{{ $value }}</option>@endforeach</select></div><div><label class="font-medium">Initial status</label><select name="status" class="mt-1 w-full rounded-xl border-slate-300"><option value="draft">Draft</option><option value="published" @selected(old('status',$challenge->status??'')==='published')>Publish</option></select></div></div>
<div class="grid gap-4 md:grid-cols-4"><div><label class="font-medium">Starts</label><input type="datetime-local" name="starts_at" required value="{{ old('starts_at',isset($challenge)?$challenge->starts_at->format('Y-m-d\TH:i'):'') }}" class="mt-1 w-full rounded-xl border-slate-300"></div><div><label class="font-medium">Submission deadline</label><input type="datetime-local" name="submission_deadline" required value="{{ old('submission_deadline',isset($challenge)&&$challenge->submission_deadline?$challenge->submission_deadline->format('Y-m-d\TH:i'):'') }}" class="mt-1 w-full rounded-xl border-slate-300"></div><div><label class="font-medium">Challenge ends</label><input type="datetime-local" name="ends_at" required value="{{ old('ends_at',isset($challenge)?$challenge->ends_at->format('Y-m-d\TH:i'):'') }}" class="mt-1 w-full rounded-xl border-slate-300"></div><div><label class="font-medium">Max team size</label><input type="number" name="max_team_members" min="2" max="50" value="{{ old('max_team_members',$challenge->max_team_members??5) }}" class="mt-1 w-full rounded-xl border-slate-300"></div></div>
<div class="grid gap-4 md:grid-cols-2"><div><label class="font-medium">Rules (one per line)</label><textarea name="rules_text" rows="6" class="mt-1 w-full rounded-xl border-slate-300">{{ old('rules_text',$editing?implode("\n",$challenge->rules??[]):'') }}</textarea></div><div><label class="font-medium">Rewards (one per line)</label><textarea name="rewards_text" rows="6" class="mt-1 w-full rounded-xl border-slate-300">{{ old('rewards_text',$editing?implode("\n",$challenge->rewards??[]):'') }}</textarea></div></div>
<div><label class="font-medium">Judging criteria</label><div class="mt-2 grid gap-2 md:grid-cols-2">@php($criteria=old('judging_criteria',$editing?($challenge->judging_criteria??[]):['Academic quality','Originality','Evidence and clarity'])) @foreach(array_pad($criteria,4,'') as $criterion)<input name="judging_criteria[]" value="{{ $criterion }}" class="rounded-xl border-slate-300" placeholder="Criterion">@endforeach</div></div>
<div class="grid gap-4 md:grid-cols-4"><div><label class="font-medium">Community</label><select name="knowledge_community_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">No community</option>@foreach($communities as $community)<option value="{{ $community->id }}" @selected(old('knowledge_community_id',$challenge->knowledge_community_id??null)==$community->id)>{{ $community->name }}</option>@endforeach</select></div><div><label class="font-medium">Group</label><select name="group_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">No group</option>@foreach($groups as $group)<option value="{{ $group->id }}" @selected(old('group_id',$challenge->group_id??null)==$group->id)>{{ $group->name }}</option>@endforeach</select></div><div><label class="font-medium">Category</label><select name="category_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">No category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id',$challenge->category_id??null)==$category->id)>{{ $category->name }}</option>@endforeach</select></div><div><label class="font-medium">Tags</label><select multiple name="tag_ids[]" class="mt-1 h-32 w-full rounded-xl border-slate-300">@foreach($tags as $tag)<option value="{{ $tag->id }}" @selected(in_array($tag->id,old('tag_ids',$editing?$challenge->tags->pluck('id')->all():[])))>{{ $tag->name }}</option>@endforeach</select></div></div>
<div><label class="font-medium">Human judges</label><select multiple name="judge_ids[]" class="mt-1 h-40 w-full rounded-xl border-slate-300">@foreach($users as $user)<option value="{{ $user->id }}" @selected(in_array($user->id,old('judge_ids',$editing?$challenge->judges->pluck('id')->all():[])))>{{ $user->full_name }}</option>@endforeach</select></div>
<div class="grid gap-3 md:grid-cols-3"><label class="flex items-center gap-2"><input type="checkbox" name="public_voting_enabled" value="1" @checked(old('public_voting_enabled',$challenge->public_voting_enabled??false))> Enable public voting</label><label class="flex items-center gap-2"><input type="checkbox" name="ai_assistance_enabled" value="1" @checked(old('ai_assistance_enabled',$challenge->ai_assistance_enabled??false))> AI advisory evidence</label><label class="flex items-center gap-2"><input type="checkbox" name="requires_moderation" value="1" @checked(old('requires_moderation',$challenge->requires_moderation??false))> Administrator moderation</label></div>
<div class="flex justify-end gap-3"><a href="{{ $editing?route('knowledge.challenges.show',$challenge):route('knowledge.challenges.index') }}" class="rounded-xl border px-5 py-3">Cancel</a><button class="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">{{ $editing?'Save challenge':'Create challenge' }}</button></div></form>
@endsection
