@extends('layouts.app')
@section('title','Academic Challenges')
@section('page-title','Academic Challenges')
@section('page-subtitle','Competitions, innovation challenges and evidence-based judging')
@section('content')
@include('knowledge._nav')
<div class="space-y-7">
    <section class="rounded-[2rem] bg-gradient-to-br from-amber-950 via-slate-950 to-orange-950 p-7 text-white shadow-xl sm:p-9"><div class="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p class="text-xs font-black uppercase tracking-[.24em] text-amber-300">Compete & create</p><h1 class="mt-2 text-3xl font-black sm:text-4xl">Academic challenges</h1><p class="mt-3 max-w-3xl text-sm leading-7 text-slate-300">Take part in structured challenges, submit work, receive human judging and follow transparent results.</p></div>@auth @can('create',App\Models\AcademicChallenge::class)<a href="{{ route('knowledge.challenges.create') }}" class="rounded-xl bg-white px-5 py-3 text-sm font-black text-slate-950">Create challenge</a>@endcan @endauth</div></section>
    <form method="GET" class="grid gap-3 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-4"><input name="q" value="{{ $filters['q']??'' }}" placeholder="Search challenges…" class="rounded-xl border-slate-300"><select name="type" class="rounded-xl border-slate-300"><option value="">All types</option>@foreach(['writing','research','tutorial','project_documentation','innovation','siwes_report'] as $type)<option value="{{ $type }}" @selected(($filters['type']??'')===$type)>{{ str($type)->headline() }}</option>@endforeach</select><select name="status" class="rounded-xl border-slate-300"><option value="">All stages</option>@foreach(['upcoming','active','judging','completed','mine'] as $status)<option value="{{ $status }}" @selected(($filters['status']??'')===$status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="rounded-xl bg-slate-900 px-4 py-2 text-sm font-black text-white">Filter</button></form>
    <div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">@forelse($challenges as $challenge)<a href="{{ route('knowledge.challenges.show',$challenge) }}" class="group flex min-h-72 flex-col rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-amber-200 hover:shadow-xl"><div class="flex items-center justify-between"><span class="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-700">{{ str($challenge->challenge_type)->headline() }}</span><span class="text-xs font-bold text-slate-400">{{ str($challenge->participation_mode)->headline() }}</span></div><h2 class="mt-5 text-xl font-black text-slate-900 group-hover:text-amber-700">{{ $challenge->title }}</h2><p class="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{{ $challenge->description }}</p><div class="mt-auto grid grid-cols-2 gap-3 border-t border-slate-100 pt-5"><div><p class="text-[10px] font-black uppercase text-slate-400">Deadline</p><p class="mt-1 text-sm font-bold text-slate-700">{{ ($challenge->submission_deadline??$challenge->ends_at)->format('M j') }}</p></div><div class="text-right"><p class="text-[10px] font-black uppercase text-slate-400">Entries</p><p class="mt-1 text-sm font-bold text-slate-700">{{ $challenge->entries_count }} · {{ str($challenge->status)->headline() }}</p></div></div></a>@empty<div class="md:col-span-2 xl:col-span-3 rounded-[2rem] border border-dashed border-slate-300 bg-white p-14 text-center"><h2 class="text-xl font-black text-slate-900">No challenges match these filters</h2><p class="mt-2 text-sm text-slate-500">Explore another category or stage.</p></div>@endforelse</div>{{ $challenges->links() }}
</div>
@endsection
