@extends('layouts.app')
@section('title','Academic Challenges')
@section('page-title','Academic Challenges')
@section('page-subtitle','Human-reviewed writing, research, tutorial, documentation and innovation competitions')
@section('content')
@include('knowledge._nav')
<div class="mb-6 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 class="text-2xl font-bold">Explore challenges</h1><p class="mt-1 text-slate-600">Join individually or with a team, save drafts, submit evidence, receive criterion-level feedback, and view verified results.</p></div>@auth @can('create',App\Models\AcademicChallenge::class)<a href="{{ route('knowledge.challenges.create') }}" class="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Create challenge</a>@endcan @endauth</div>
<form method="GET" class="mb-6 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-5"><input name="q" value="{{ $filters['q']??'' }}" placeholder="Search challenges" class="rounded-xl border-slate-300 md:col-span-2"><select name="type" class="rounded-xl border-slate-300"><option value="">All types</option>@foreach(['writing','research','tutorial','project_documentation','innovation','siwes_report'] as $type)<option value="{{ $type }}" @selected(($filters['type']??'')===$type)>{{ str($type)->headline() }}</option>@endforeach</select><select name="status" class="rounded-xl border-slate-300"><option value="">All active</option>@foreach(['upcoming','active','judging','completed','mine'] as $status)<option value="{{ $status }}" @selected(($filters['status']??'')===$status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="rounded-xl border border-blue-600 px-4 py-2 font-semibold text-blue-700">Filter</button></form>
<div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">@forelse($challenges as $challenge)<a class="rounded-2xl border bg-white p-5 shadow-sm hover:border-blue-300" href="{{ route('knowledge.challenges.show',$challenge) }}"><div class="flex justify-between"><span class="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-medium text-blue-700">{{ str($challenge->challenge_type)->headline() }}</span><span class="text-xs text-slate-500">{{ ucfirst($challenge->participation_mode) }}</span></div><h2 class="mt-4 text-xl font-bold">{{ $challenge->title }}</h2><p class="mt-2 line-clamp-3 text-sm text-slate-600">{{ $challenge->description }}</p><p class="mt-4 text-xs text-slate-500">Deadline {{ ($challenge->submission_deadline??$challenge->ends_at)->diffForHumans() }} · {{ $challenge->entries_count }} final entries · {{ ucfirst($challenge->status) }}</p></a>@empty<div class="rounded-2xl border border-dashed bg-white p-10 text-center md:col-span-3">No challenges match these filters.</div>@endforelse</div><div class="mt-6">{{ $challenges->links() }}</div>
@endsection
