@extends('layouts.app')
@section('title','Specialized research workspace')
@section('page-title','SIWES and seminar workspace')
@section('page-subtitle',$research->title)
@section('content')
<div class="space-y-6">
  <div class="flex flex-wrap gap-3"><a href="{{ route('research.show',$research) }}" class="rounded-xl border px-4 py-2">Writing workspace</a><a href="{{ route('research.workspace',$research) }}" class="rounded-xl border px-4 py-2">Control center</a></div>

  <section class="rounded-2xl border bg-white p-5">
    <h2 class="text-xl font-semibold">SIWES placement and logbook</h2>
    <div class="mt-4">
      @include('ai._contextual-assistant', [
          'assistantFeature' => 'siwes_assistant',
          'assistantEndpoint' => route('ai.context.siwes', $research),
      ])
    </div>
    @if(!$placement)
      <form method="POST" action="{{ route('research.siwes.placements.store',$research) }}" class="mt-4 grid gap-3 md:grid-cols-2">@csrf
        <select name="submission_id" required class="rounded-xl border-slate-300"><option value="">Select existing SIWES submission</option>@foreach($eligibleSubmissions->where('type','siwes') as $submission)<option value="{{ $submission->id }}">{{ $submission->title }}</option>@endforeach</select>
        <input name="organization_name" required class="rounded-xl border-slate-300" placeholder="Organization name">
        <textarea name="organization_address" class="rounded-xl border-slate-300" placeholder="Organization address"></textarea><input name="industry_sector" class="rounded-xl border-slate-300" placeholder="Industry sector">
        <input name="industry_supervisor_name" class="rounded-xl border-slate-300" placeholder="Industry supervisor"><input type="email" name="industry_supervisor_email" class="rounded-xl border-slate-300" placeholder="Supervisor email">
        <input name="industry_supervisor_phone" class="rounded-xl border-slate-300" placeholder="Supervisor phone"><input type="number" name="required_hours" min="0" class="rounded-xl border-slate-300" placeholder="Required hours">
        <input type="date" name="started_on" class="rounded-xl border-slate-300"><input type="date" name="ended_on" class="rounded-xl border-slate-300">
        <button class="rounded-xl bg-indigo-600 px-4 py-2 text-white md:col-span-2">Connect SIWES placement</button>
      </form>
    @else
      <div class="mt-4 grid gap-4 md:grid-cols-4"><div><p class="text-xs text-slate-500">Organization</p><p class="font-medium">{{ $placement->organization_name }}</p></div><div><p class="text-xs text-slate-500">Supervisor</p><p>{{ $placement->industry_supervisor_name ?: 'Not set' }}</p></div><div><p class="text-xs text-slate-500">Hours</p><p>{{ $placement->completed_hours }} / {{ $placement->required_hours }}</p></div><div><p class="text-xs text-slate-500">Period</p><p>{{ $placement->started_on?->format('M j, Y') }} – {{ $placement->ended_on?->format('M j, Y') }}</p></div></div>
      <div class="mt-6 grid gap-5 xl:grid-cols-2">
        <div><h3 class="font-semibold">Add logbook entry</h3><form method="POST" action="{{ route('research.siwes.logs.store',[$research,$placement]) }}" class="mt-3 grid gap-2">@csrf<input type="date" name="entry_date" required class="rounded-xl border-slate-300"><div class="grid grid-cols-2 gap-2"><select name="period_type" class="rounded-xl border-slate-300"><option>daily</option><option>weekly</option><option>monthly</option></select><input type="number" name="hours" min="0" max="168" required class="rounded-xl border-slate-300" placeholder="Hours"></div><input name="title" required class="rounded-xl border-slate-300" placeholder="Activity title"><textarea name="activities" required class="rounded-xl border-slate-300" placeholder="Activities performed"></textarea><textarea name="skills_learned" class="rounded-xl border-slate-300" placeholder="Skills learned"></textarea><textarea name="challenges" class="rounded-xl border-slate-300" placeholder="Challenges"></textarea><select name="status" class="rounded-xl border-slate-300"><option>draft</option><option>submitted</option></select><button class="rounded-xl bg-indigo-600 px-4 py-2 text-white">Save logbook entry</button></form></div>
        <div><h3 class="font-semibold">Attendance</h3><form method="POST" action="{{ route('research.siwes.attendance.store',[$research,$placement]) }}" class="mt-3 grid gap-2">@csrf<input type="date" name="attendance_date" required class="rounded-xl border-slate-300"><div class="grid grid-cols-2 gap-2"><input type="time" name="check_in_at" class="rounded-xl border-slate-300"><input type="time" name="check_out_at" class="rounded-xl border-slate-300"></div><div class="grid grid-cols-2 gap-2"><input type="number" step="0.01" name="hours_worked" required class="rounded-xl border-slate-300" placeholder="Hours worked"><select name="status" class="rounded-xl border-slate-300"><option>present</option><option>remote</option><option>absent</option><option>excused</option></select></div><textarea name="note" class="rounded-xl border-slate-300" placeholder="Attendance note"></textarea><button class="rounded-xl border px-4 py-2">Record attendance</button></form></div>
      </div>
      <div class="mt-6 space-y-3"><h3 class="font-semibold">Logbook history</h3>@foreach($placement->logs->sortByDesc('entry_date') as $log)<article class="rounded-xl border p-4"><div class="flex justify-between"><p class="font-medium">{{ $log->entry_date?->format('M j, Y') }} · {{ $log->title }}</p><span class="rounded-full bg-slate-100 px-2 py-1 text-xs">{{ $log->status }}</span></div><p class="mt-2 text-sm">{{ $log->activities }}</p>@can('review',$research)<form method="POST" action="{{ route('research.siwes.logs.review',[$research,$log]) }}" class="mt-3 grid gap-2 md:grid-cols-[180px_1fr_auto]">@csrf<select name="status" class="rounded-lg border-slate-300"><option value="approved">Approve</option><option value="revision_requested">Request revision</option><option value="rejected">Reject</option></select><input name="lecturer_comment" class="rounded-lg border-slate-300" placeholder="Lecturer comment"><button class="rounded-lg bg-slate-900 px-3 text-white">Review</button></form>@endcan</article>@endforeach</div>
      @can('review',$research)<form method="POST" action="{{ route('research.siwes.evaluations.store',[$research,$placement]) }}" class="mt-6 grid gap-2 md:grid-cols-3">@csrf<select name="evaluator_type" class="rounded-xl border-slate-300"><option>lecturer</option><option>department</option><option>industry_supervisor</option></select>@foreach(['attendance_score','technical_score','conduct_score','report_score'] as $score)<input type="number" min="0" max="100" step="0.01" name="{{ $score }}" class="rounded-xl border-slate-300" placeholder="{{ str($score)->headline() }}">@endforeach<textarea name="comment" class="rounded-xl border-slate-300 md:col-span-2" placeholder="Evaluation comment"></textarea><button class="rounded-xl bg-emerald-600 px-4 py-2 text-white">Submit evaluation</button></form>@endcan
    @endif
  </section>

  <section class="rounded-2xl border bg-white p-5">
    <h2 class="text-xl font-semibold">Seminar schedule, panel, questions, and marks</h2>
    @if(!$seminar)
      @can('review',$research)<form method="POST" enctype="multipart/form-data" action="{{ route('research.seminar.store',$research) }}" class="mt-4 grid gap-3 md:grid-cols-2">@csrf<select name="submission_id" required class="rounded-xl border-slate-300"><option value="">Select existing seminar submission</option>@foreach($eligibleSubmissions->where('type','seminar') as $submission)<option value="{{ $submission->id }}">{{ $submission->title }}</option>@endforeach</select><input name="title" required class="rounded-xl border-slate-300" placeholder="Seminar title"><input type="datetime-local" name="scheduled_at" required class="rounded-xl border-slate-300"><input type="number" name="duration_minutes" value="30" min="10" class="rounded-xl border-slate-300"><input name="venue" class="rounded-xl border-slate-300" placeholder="Venue"><input type="url" name="online_url" class="rounded-xl border-slate-300" placeholder="Online URL"><select multiple name="panel_user_ids[]" class="rounded-xl border-slate-300 md:col-span-2">@foreach($panelUsers as $person)<option value="{{ $person->id }}">{{ $person->full_name }}</option>@endforeach</select><input type="file" name="slides" class="rounded-xl border p-2 md:col-span-2"><button class="rounded-xl bg-indigo-600 px-4 py-2 text-white md:col-span-2">Schedule seminar</button></form>@endcan
    @else
      <div class="mt-4 grid gap-4 md:grid-cols-4"><div><p class="text-xs text-slate-500">When</p><p>{{ $seminar->scheduled_at?->toDayDateTimeString() }}</p></div><div><p class="text-xs text-slate-500">Venue</p><p>{{ $seminar->venue ?: $seminar->online_url }}</p></div><div><p class="text-xs text-slate-500">Status</p><p>{{ str($seminar->status)->headline() }}</p></div><div><p class="text-xs text-slate-500">Panel average</p><p>{{ $seminar->final_score ?? 'Pending' }}</p></div></div>
      <div class="mt-6 grid gap-6 xl:grid-cols-2"><div><h3 class="font-semibold">Panel scoring</h3>@foreach($seminar->panelMembers as $panel)<form method="POST" action="{{ route('research.seminar.panel.score',[$research,$seminar,$panel]) }}" class="mt-2 grid gap-2 rounded-xl border p-3 md:grid-cols-[1fr_100px_1fr_auto]">@csrf<span>{{ $panel->user?->full_name }}</span><input type="number" name="score" value="{{ $panel->score }}" min="0" max="100" step="0.01" class="rounded-lg border-slate-300"><input name="comment" value="{{ $panel->comment }}" class="rounded-lg border-slate-300" placeholder="Panel comment"><button class="rounded-lg border px-3">Save</button></form>@endforeach</div><div><h3 class="font-semibold">Questions</h3><form method="POST" action="{{ route('research.seminar.questions.store',[$research,$seminar]) }}" class="mt-2 flex gap-2">@csrf<input name="question" required class="flex-1 rounded-xl border-slate-300" placeholder="Record a question"><button class="rounded-xl border px-4">Add</button></form>@foreach($seminar->questions as $question)<article class="mt-2 rounded-xl bg-slate-50 p-3"><p class="font-medium">{{ $question->question }}</p>@if($question->response)<p class="mt-1 text-sm">{{ $question->response }}</p>@else<form method="POST" action="{{ route('research.seminar.questions.answer',[$research,$question]) }}" class="mt-2 flex gap-2">@csrf<input name="response" required class="flex-1 rounded-lg border-slate-300" placeholder="Response"><button class="rounded-lg border px-3">Answer</button></form>@endif</article>@endforeach</div></div>
      @can('review',$research)<form method="POST" action="{{ route('research.seminar.complete',[$research,$seminar]) }}" class="mt-6 grid gap-2 md:grid-cols-[220px_1fr_auto]">@csrf<select name="status" class="rounded-xl border-slate-300"><option value="completed">Complete and grade</option><option value="corrections_required">Corrections required</option><option value="cancelled">Cancel</option></select><input name="moderator_notes" class="rounded-xl border-slate-300" placeholder="Moderator notes or correction instructions"><button class="rounded-xl bg-emerald-600 px-4 text-white">Finalize</button></form>@endcan
    @endif
  </section>
</div>
@endsection
