<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Course Grades - {{ $course->name }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h1 { color: #333; border-bottom: 1px solid #ccc; padding-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ccc; padding: 8px; text-align: left; }
        th { background-color: #f5f5f5; }
        .footer { margin-top: 30px; font-size: 12px; color: #666; }
    </style>
</head>
<body>
    <h1>Course Grades: {{ $course->name }} ({{ $course->code }})</h1>
    <p>Generated At: {{ $generated_at->format('Y-m-d H:i:s') }}</p>

    <table>
        <thead>
            <tr>
                <th>Student ID</th>
                <th>Student Name</th>
                <th>Submission Title</th>
                <th>Type</th>
                <th>Score</th>
                <th>Max Score</th>
                <th>Submitted At</th>
                <th>Graded At</th>
            </tr>
        </thead>
        <tbody>
            @foreach($submissions as $sub)
                <tr>
                    <td>{{ $sub->user->student_id ?? 'N/A' }}</td>
                    <td>{{ $sub->user->first_name }} {{ $sub->user->last_name }}</td>
                    <td>{{ $sub->title }}</td>
                    <td>{{ ucfirst($sub->type) }}</td>
                    <td>{{ $sub->grade?->score ?? 'N/A' }}</td>
                    <td>{{ $sub->grade?->max_score ?? 100 }}</td>
                    <td>{{ $sub->submitted_at?->format('Y-m-d H:i:s') ?? 'N/A' }}</td>
                    <td>{{ $sub->graded_at?->format('Y-m-d H:i:s') ?? 'N/A' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Total Submissions: {{ $submissions->count() }}</p>
        <p>Generated by {{ \App\Services\SettingService::get('site_name', 'AcadFlow') }}</p>
    </div>
</body>
</html>
