<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Course Materials - {{ $course->name }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; margin: 40px; }
        h1 { color: #333; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; }
        .info { background: #f9f9f9; padding: 15px; border-radius: 5px; margin-top: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; font-size: 12px; }
        th { background-color: #f4f4f4; }
        .footer { margin-top: 50px; text-align: center; color: #888; font-size: 12px; }
        .type-badge { 
            display: inline-block; 
            padding: 2px 8px; 
            border-radius: 3px; 
            font-size: 10px; 
            background: #e0e7ff; 
            color: #3730a3;
        }
    </style>
</head>
<body>
    <h1>Course Materials Index</h1>

    <div class="info">
        <strong>Course:</strong> {{ $course->code }} - {{ $course->name }}<br>
        <strong>Generated:</strong> {{ $generated_at->format('M d, Y H:i') }}
    </div>

    <table>
        <thead>
            <tr>
                <th>Type</th>
                <th>Title</th>
                <th>Topic</th>
                <th>Week</th>
                <th>File Size</th>
                <th>Uploaded By</th>
                <th>Downloads</th>
            </tr>
        </thead>
        <tbody>
            @foreach($materials as $material)
                <tr>
                    <td><span class="type-badge">{{ ucfirst(str_replace('_', ' ', $material->type)) }}</span></td>
                    <td>{{ $material->title }}</td>
                    <td>{{ $material->topic ?? '-' }}</td>
                    <td>{{ $material->week_number ?? '-' }}</td>
                    <td>{{ number_format($material->file_size / 1024, 2) }} KB</td>
                    <td>{{ $material->uploader->full_name ?? 'Unknown' }}</td>
                    <td>{{ $material->download_count }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Total: {{ $materials->count() }} materials<br>
        Generated by {{ \App\Services\SettingService::get('site_name', 'UniAcademic') }} Academic Management System
    </div>
</body>
</html>
