<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Grade Report - {{ $submission->title }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; margin: 40px; }
        h1 { color: #333; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; }
        .info { background: #f9f9f9; padding: 15px; border-radius: 5px; margin-top: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        th { background-color: #f4f4f4; }
        .grade-box { 
            border: 2px solid #4f46e5; 
            padding: 20px; 
            text-align: center; 
            font-size: 24px; 
            margin-top: 20px;
            border-radius: 5px;
        }
        .footer { margin-top: 50px; text-align: center; color: #888; font-size: 12px; }
    </style>
</head>
<body>
    <h1>Grade Report</h1>

    <div class="info">
        <strong>Submission:</strong> {{ $submission->title }}<br>
        <strong>Course:</strong> {{ $submission->course->code }} - {{ $submission->course->name }}<br>
        <strong>Student:</strong> {{ $submission->user->full_name }} ({{ $submission->user->email }})<br>
        <strong>Submitted:</strong> {{ $submission->submitted_at?->format('M d, Y H:i') ?? 'Not submitted' }}<br>
        <strong>Status:</strong> {{ ucfirst(str_replace('_', ' ', $submission->status)) }}
    </div>

    @if($submission->grade !== null)
        <div class="grade-box">
            Grade: {{ $submission->grade }}/{{ $submission->task->max_score ?? 100 }}
        </div>
    @endif

    @if($submission->feedback)
        <h2>Feedback</h2>
        <div style="padding: 15px; background: #f9f9f9; border-radius: 5px;">
            {!! nl2br(e($submission->feedback)) !!}
        </div>
    @endif

    <h2>Submission Details</h2>
    <table>
        <tr><th>Field</th><th>Value</th></tr>
        <tr><td>Attempt</td><td>{{ $submission->attempt_number }}</td></tr>
        <tr><td>Similarity Score</td><td>{{ $submission->similarity_score ?? 'N/A' }}%</td></tr>
        <tr><td>Late Submission</td><td>{{ $submission->is_late ? 'Yes' : 'No' }}</td></tr>
    </table>

    <div class="footer">
        Generated by {{ \App\Services\SettingService::get('site_name', 'UniAcademic') }} Academic Management System
    </div>
</body>
</html>
