<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Transcript - {{ $student->full_name }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; margin: 40px; }
        h1 { color: #333; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; }
        h2 { color: #555; margin-top: 30px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        th { background-color: #f4f4f4; }
        .summary { background: #f9f9f9; padding: 15px; border-radius: 5px; margin-top: 20px; }
        .footer { margin-top: 50px; text-align: center; color: #888; font-size: 12px; }
    </style>
</head>
<body>
    <h1>Academic Transcript</h1>

    <div>
        <strong>Student:</strong> {{ $student->full_name }}<br>
        <strong>Student ID:</strong> {{ $student->student_id ?? 'N/A' }}<br>
        <strong>Email:</strong> {{ $student->email }}<br>
        <strong>Generated:</strong> {{ $generated_at->format('M d, Y H:i') }}
    </div>

    <h2>Course Submissions</h2>
    <table>
        <thead>
            <tr>
                <th>Course</th>
                <th>Assignment</th>
                <th>Status</th>
                <th>Grade</th>
                <th>Submitted</th>
            </tr>
        </thead>
        <tbody>
            @forelse($submissions as $submission)
                <tr>
                    <td>{{ $submission->course->code }} - {{ $submission->course->name }}</td>
                    <td>{{ $submission->task->title ?? 'N/A' }}</td>
                    <td>{{ ucfirst(str_replace('_', ' ', $submission->status)) }}</td>
                    <td>{{ $submission->grade ?? 'Pending' }}</td>
                    <td>{{ $submission->submitted_at?->format('M d, Y') ?? 'Not submitted' }}</td>
                </tr>
            @empty
                <tr><td colspan="5">No submissions found.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="summary">
        <strong>Summary:</strong> {{ $submissions->count() }} total submissions,
        {{ $submissions->where('status', 'graded')->count() }} graded
    </div>

    <div class="footer">
        Generated by UniFlow Academic Management System
    </div>
</body>
</html>
