<?php

return [
    /*
    |--------------------------------------------------------------------------
    | AcadFlow Feature / Module Registry
    |--------------------------------------------------------------------------
    |
    | This registry is metadata and route mapping only. Runtime state is stored
    | in the existing `feature_flags` table. Do not add availability switches
    | to other settings tables; FeatureAccessService is the single runtime
    | source of truth.
    |
    | Core recovery infrastructure (authentication, authorization, onboarding,
    | account security, admin settings and this feature-management area) is
    | intentionally not registered and therefore cannot be disabled here.
    |
    */
    'definitions' => [
        'dashboard' => [
            'title' => 'Dashboards',
            'category' => 'Core Academic',
            'description' => 'Student, lecturer, member and role-specific dashboard views.',
            'default_status' => 'enabled',
            'routes' => ['dashboard'],
            'paths' => [],
            'depends_on' => [],
            'impact' => 'Normal users will not be able to open their dashboard while this feature is unavailable.',
        ],
        'courses' => [
            'title' => 'Courses & Enrolment',
            'category' => 'Core Academic',
            'description' => 'Course lists, course details, lecturer course workspaces, enrolment and invitation flows.',
            'default_status' => 'enabled',
            'routes' => ['courses.*', 'lecturer.courses*', 'admin.courses*'],
            'paths' => ['api/v1/courses*'],
            'depends_on' => [],
            'impact' => 'Students and lecturers will lose access to course workspaces and course API actions.',
        ],
        'course_materials' => [
            'title' => 'Course Materials',
            'category' => 'Core Academic',
            'description' => 'Course resources, lecturer material management, previews, downloads and exports.',
            'default_status' => 'enabled',
            'routes' => ['materials.*', 'lecturer.materials.*'],
            'paths' => [],
            'depends_on' => ['courses'],
            'impact' => 'Course material browsing, upload, editing and download actions will be unavailable to normal users.',
        ],
        'assignments' => [
            'title' => 'Assignments',
            'category' => 'Core Academic',
            'description' => 'Assignment creation, publication, attachments, extensions and student assignment views.',
            'default_status' => 'enabled',
            'routes' => ['submission-tasks.*', 'courses.assignments'],
            'paths' => [],
            'depends_on' => ['courses'],
            'impact' => 'Students cannot open assignments and lecturers cannot create or manage them.',
        ],
        'submissions' => [
            'title' => 'Submissions & Grading',
            'category' => 'Core Academic',
            'description' => 'Student submissions, versions, lecturer review, grading, correction and approval workflows.',
            'default_status' => 'enabled',
            'routes' => ['submissions.*', 'submission-versions.*'],
            'paths' => ['api/v1/submissions*'],
            'depends_on' => ['courses', 'assignments'],
            'impact' => 'Students cannot submit work and lecturers cannot review or grade submissions.',
        ],
        'attendance' => [
            'title' => 'Attendance',
            'category' => 'Core Academic',
            'description' => 'Attendance sessions, QR/check-in, records, lecturer controls and attendance exports.',
            'default_status' => 'enabled',
            'routes' => ['attendance.*'],
            'paths' => ['api/v1/attendance*'],
            'depends_on' => ['courses'],
            'impact' => 'Attendance sessions, check-in and attendance records will be unavailable to normal users.',
        ],
        'course_discussions' => [
            'title' => 'Course Discussions',
            'category' => 'Communication',
            'description' => 'Course discussion boards, replies, reactions, subscriptions and reports.',
            'default_status' => 'enabled',
            'routes' => ['discussions.*'],
            'paths' => [],
            'depends_on' => ['courses'],
            'impact' => 'Course discussion and reply actions will be unavailable to normal users.',
        ],
        'group_collaboration' => [
            'title' => 'Groups & Collaboration',
            'category' => 'Collaboration',
            'description' => 'Groups, memberships, invitations, tasks, resources, comments and collaboration workflows.',
            'default_status' => 'enabled',
            'routes' => ['groups.*'],
            'paths' => [],
            'depends_on' => [],
            'impact' => 'Group workspaces and collaboration actions will be unavailable to normal users.',
        ],
        'research_studio' => [
            'title' => 'Research Studio',
            'category' => 'Research Studio',
            'description' => 'Research projects, structured writing, literature, meetings, milestones, archives and workflow controls.',
            'default_status' => 'enabled',
            'routes' => ['research.*'],
            'paths' => ['api/v1/research-projects*'],
            'depends_on' => [],
            'impact' => 'Research workspaces and research API actions will be unavailable to normal users.',
        ],
        'research_to_knowledge_hub' => [
            'title' => 'Research → Knowledge Hub Publishing',
            'category' => 'Research Studio',
            'description' => 'Publishes approved research into linked Knowledge Hub drafts.',
            'default_status' => 'enabled',
            'routes' => ['research.publish'],
            'paths' => ['api/v1/research-projects/*/publish'],
            'depends_on' => ['research_studio', 'knowledge_hub'],
            'impact' => 'Publishing research into Knowledge Hub drafts will be unavailable to normal users.',
        ],
        'siwes_module' => [
            'title' => 'SIWES Workspace',
            'category' => 'Research Studio',
            'description' => 'SIWES placements, logs, attendance and evaluations within Research Studio.',
            'default_status' => 'enabled',
            'routes' => ['research.siwes.*'],
            'paths' => [],
            'depends_on' => ['research_studio'],
            'impact' => 'SIWES placement, logbook and evaluation actions will be unavailable to normal users.',
        ],
        'seminar_module' => [
            'title' => 'Seminar Workspace',
            'category' => 'Research Studio',
            'description' => 'Seminar scheduling, panels, questions, scoring and completion workflows.',
            'default_status' => 'enabled',
            'routes' => ['research.seminar.*'],
            'paths' => [],
            'depends_on' => ['research_studio'],
            'impact' => 'Seminar workflows will be unavailable to normal users.',
        ],
        'final_year_project' => [
            'title' => 'Project Defense',
            'category' => 'Research Studio',
            'description' => 'Final-year project defense scheduling and related defense workflow actions.',
            'default_status' => 'enabled',
            'routes' => ['defenses.*', 'research.defenses.*'],
            'paths' => [],
            'depends_on' => ['research_studio'],
            'impact' => 'Project defense scheduling and defense actions will be unavailable to normal users.',
        ],
        'knowledge_hub' => [
            'title' => 'Knowledge Hub',
            'category' => 'Knowledge Hub',
            'description' => 'Academic publishing, discovery, creator profiles, comments, reactions, citations and publication management.',
            'default_status' => 'enabled',
            'routes' => [
                'knowledge.index', 'knowledge.search', 'knowledge.show', 'knowledge.creator*',
                'knowledge.leaderboard', 'knowledge.follow', 'knowledge.reactions', 'knowledge.comments.*',
                'knowledge.citations.*', 'knowledge.reports', 'knowledge.manage*', 'knowledge.verification.*',
                'knowledge.shares',
            ],
            'paths' => ['api/v1/knowledge*'],
            'depends_on' => [],
            'impact' => 'Knowledge discovery, publishing and related API actions will be unavailable to normal users.',
        ],
        'knowledge_communities' => [
            'title' => 'Knowledge Communities',
            'category' => 'Knowledge Hub',
            'description' => 'Communities, community posts, polls, memberships, invitations, comments and moderation.',
            'default_status' => 'enabled',
            'routes' => ['knowledge.communities.*', 'knowledge.community-posts.*', 'knowledge.polls.*'],
            'paths' => [],
            'depends_on' => ['knowledge_hub'],
            'impact' => 'Community pages, posts and polls will be unavailable to normal users.',
        ],
        'learning_paths' => [
            'title' => 'Learning Paths',
            'category' => 'Knowledge Hub',
            'description' => 'Curated learning paths, enrolment, learning items and learner progress.',
            'default_status' => 'enabled',
            'routes' => ['knowledge.learning.*'],
            'paths' => [],
            'depends_on' => ['knowledge_hub'],
            'impact' => 'Learning paths and learner progress actions will be unavailable to normal users.',
        ],
        'reading_lists' => [
            'title' => 'Reading Lists',
            'category' => 'Knowledge Hub',
            'description' => 'Reading-list creation, sharing, members, exports and list items.',
            'default_status' => 'enabled',
            'routes' => ['knowledge.reading.*'],
            'paths' => [],
            'depends_on' => ['knowledge_hub'],
            'impact' => 'Reading lists and their sharing/export actions will be unavailable to normal users.',
        ],
        'academic_events' => [
            'title' => 'Academic Events & Calendar',
            'category' => 'Knowledge Hub',
            'description' => 'Academic events, registrations, invitations, attendance and event calendar views.',
            'default_status' => 'enabled',
            'routes' => ['knowledge.events.*'],
            'paths' => [],
            'depends_on' => ['knowledge_hub'],
            'impact' => 'Academic event discovery, registration and event-management actions will be unavailable to normal users.',
        ],
        'academic_challenges' => [
            'title' => 'Academic Challenges',
            'category' => 'Knowledge Hub',
            'description' => 'Challenges, entries, judging, voting, comments and results.',
            'default_status' => 'enabled',
            'routes' => ['knowledge.challenges.*'],
            'paths' => [],
            'depends_on' => ['knowledge_hub'],
            'impact' => 'Academic challenge participation and challenge-management actions will be unavailable to normal users.',
        ],
        'course_certificates' => [
            'title' => 'Certificates',
            'category' => 'Knowledge Hub',
            'description' => 'Certificate verification and downloadable academic certificates.',
            'default_status' => 'enabled',
            'routes' => ['knowledge.certificates.*'],
            'paths' => [],
            'depends_on' => ['knowledge_hub'],
            'impact' => 'Certificate verification and downloads will be unavailable to normal users.',
        ],
        'knowledge_ai_companion' => [
            'title' => 'Knowledge AI Companion',
            'category' => 'AI & Intelligence',
            'description' => 'Context-grounded AI companion inside Knowledge Hub resources.',
            'default_status' => 'enabled',
            'routes' => ['knowledge.companion.*'],
            'paths' => ['api/v1/knowledge/*/companion'],
            'depends_on' => ['knowledge_hub', 'ai_assistant'],
            'impact' => 'The AI companion inside Knowledge Hub resources will be unavailable to normal users.',
        ],
        'ai_assistant' => [
            'title' => 'AI Assistant',
            'category' => 'AI & Intelligence',
            'description' => 'AcadFlow AI workspace plus centralized student, lecturer, writing, citation, research, assignment, SIWES, project, material and discussion AI assistance.',
            'default_status' => 'enabled',
            'routes' => ['ai.assistant', 'ai.assistant.*', 'ai.writing', 'ai.citation', 'ai.submission.*', 'ai.context.*'],
            'paths' => [],
            'depends_on' => [],
            'impact' => 'AI Assistant and user-facing AI assistance will be unavailable to normal users. AI Settings remain accessible to administrators.',
        ],
        'notifications' => [
            'title' => 'Notifications',
            'category' => 'Communication',
            'description' => 'Notification centre, user preferences, admin announcements and notification management.',
            'default_status' => 'enabled',
            'routes' => ['notifications.*', 'admin.notifications.*'],
            'paths' => ['api/v1/notifications*'],
            'depends_on' => [],
            'impact' => 'The notification centre and notification API actions will be unavailable to normal users.',
        ],
        'push_notifications' => [
            'title' => 'Push Notifications',
            'category' => 'Communication',
            'description' => 'Browser/mobile push subscription, unsubscribe, VAPID key and push-test endpoints.',
            'default_status' => 'enabled',
            'routes' => [],
            'paths' => ['api/v1/push*'],
            'depends_on' => ['notifications'],
            'impact' => 'Push subscription and push-delivery endpoints will be unavailable to normal users.',
        ],
        'billing_subscriptions' => [
            'title' => 'Billing & Subscriptions',
            'category' => 'Commerce',
            'description' => 'Invoices, subscription plans, checkout, upgrades, cancellations and institutional billing views.',
            'default_status' => 'enabled',
            'routes' => [
                'billing.*', 'subscription.show', 'subscription.checkout', 'subscription.initiate-payment',
                'subscription.payment.callback', 'subscription.process-upgrade', 'subscription.upgrade',
                'subscription.cancel', 'admin.billing', 'admin.subscriptions', 'admin.subscription-reports.*',
            ],
            'paths' => ['api/v1/invoices*', 'api/v1/payments*', 'api/v1/subscriptions*'],
            'depends_on' => [],
            'impact' => 'Users cannot access billing/subscription screens or initiate new billing API actions. Existing payment webhooks remain reachable for safe reconciliation.',
        ],
        'knowledge_hub_premium' => [
            'title' => 'Premium Knowledge Resources',
            'category' => 'Commerce',
            'description' => 'Paid/premium Knowledge Hub resources and premium entitlement checks.',
            'default_status' => 'disabled',
            'routes' => [],
            'paths' => [],
            'depends_on' => ['knowledge_hub'],
            'impact' => 'Premium Knowledge Hub resources will not be available for purchase/access by normal users.',
        ],
        'commerce_marketplace' => [
            'title' => 'Marketplace, Wallet & Payouts',
            'category' => 'Commerce',
            'description' => 'Knowledge purchases, learning purchases, orders, wallet, payout accounts, withdrawals and refunds.',
            'default_status' => 'enabled',
            'routes' => [
                'commerce.purchase', 'commerce.learning.purchase', 'commerce.orders', 'commerce.wallet',
                'commerce.payout-accounts.*', 'commerce.withdrawals.*', 'commerce.refunds.*', 'commerce.callback',
            ],
            'paths' => [],
            'depends_on' => ['knowledge_hub'],
            'impact' => 'Marketplace purchases, wallet and payout/refund actions will be unavailable to normal users. Webhooks remain available for safe reconciliation.',
        ],
        'documents_exports' => [
            'title' => 'Documents & Academic Exports',
            'category' => 'Utilities',
            'description' => 'Generated documents, transcripts, grade reports, batch exports and document downloads.',
            'default_status' => 'enabled',
            'routes' => ['documents.*', 'export.grade-report', 'export.transcript'],
            'paths' => ['api/v1/documents*'],
            'depends_on' => [],
            'impact' => 'Document generation, academic exports and document API actions will be unavailable to normal users.',
        ],
        'advanced_analytics' => [
            'title' => 'Reports & Advanced Analytics',
            'category' => 'Reporting',
            'description' => 'Administrative reports, AI analytics and reporting/export API endpoints.',
            'default_status' => 'enabled',
            'routes' => ['admin.reports*', 'ai.analytics'],
            'paths' => ['api/v1/reports*'],
            'depends_on' => [],
            'impact' => 'Reporting and analytics views/API endpoints will be unavailable to normal non-admin consumers. Administrators retain preview access.',
        ],
        'pwa_enabled' => [
            'title' => 'Progressive Web App (PWA)',
            'category' => 'Mobile & PWA',
            'description' => 'PWA installation prompt, service-worker registration and offline application capability.',
            'default_status' => 'enabled',
            'routes' => [],
            'paths' => [],
            'depends_on' => [],
            'impact' => 'PWA installation and service-worker registration will be disabled for normal users. The web application itself remains available.',
        ],
    ],
];
