@extends('layouts.app')
@php($editing=isset($event))
@section('title',$editing?'Edit Event':'Organise Event')
@section('page-title',$editing?'Edit Event':'Organise Event')
@section('page-subtitle','Create a complete event with ownership, capacity, registration and reminders')
@section('content')
@include('knowledge._nav')
<form method="POST" enctype="multipart/form-data" action="{{ $editing?route('knowledge.events.update',$event):route('knowledge.events.store') }}" class="mx-auto max-w-5xl space-y-6 rounded-2xl border bg-white p-6">@csrf @if($editing)@method('PUT')@endif
<div><label class="font-medium">Event title</label><input name="title" required value="{{ old('title',$event->title??'') }}" class="mt-1 w-full rounded-xl border-slate-300"></div><div><label class="font-medium">Event cover image</label><input type="file" name="cover_image" accept="image/jpeg,image/png,image/webp" class="mt-1 w-full rounded-xl border border-slate-300 p-2"><p class="mt-1 text-xs text-slate-500">JPG, PNG or WebP, up to 8 MB. Existing covers remain unless replaced.</p></div>
<div><label class="font-medium">Description</label><textarea name="description" required rows="6" class="mt-1 w-full rounded-xl border-slate-300">{{ old('description',$event->description??'') }}</textarea></div>
<div class="grid gap-4 md:grid-cols-4"><div><label class="font-medium">Type</label><select name="event_type" class="mt-1 w-full rounded-xl border-slate-300">@foreach(['seminar','conference','guest_lecture','research_presentation','project_defense','siwes_orientation','workshop','hackathon','competition','training'] as $type)<option value="{{ $type }}" @selected(old('event_type',$event->event_type??'seminar')===$type)>{{ str($type)->headline() }}</option>@endforeach</select></div><div><label class="font-medium">Format</label><select name="format" class="mt-1 w-full rounded-xl border-slate-300">@foreach(['physical','online','hybrid'] as $value)<option @selected(old('format',$event->format??'physical')===$value)>{{ $value }}</option>@endforeach</select></div><div><label class="font-medium">Visibility</label><select name="visibility" class="mt-1 w-full rounded-xl border-slate-300">@foreach(['public','institution','private'] as $value)<option @selected(old('visibility',$event->visibility??'public')===$value)>{{ $value }}</option>@endforeach</select></div><div><label class="font-medium">Initial status</label><select name="status" class="mt-1 w-full rounded-xl border-slate-300"><option value="draft">Draft</option><option value="published" @selected(old('status',$event->status??'')==='published')>Publish</option></select></div></div>
<div class="grid gap-4 md:grid-cols-3"><div><label class="font-medium">Starts</label><input type="datetime-local" name="starts_at" required value="{{ old('starts_at',isset($event)?$event->starts_at->format('Y-m-d\TH:i'):'') }}" class="mt-1 w-full rounded-xl border-slate-300"></div><div><label class="font-medium">Ends</label><input type="datetime-local" name="ends_at" value="{{ old('ends_at',isset($event)&&$event->ends_at?$event->ends_at->format('Y-m-d\TH:i'):'') }}" class="mt-1 w-full rounded-xl border-slate-300"></div><div><label class="font-medium">Timezone</label><input name="timezone" required value="{{ old('timezone',$event->timezone??config('app.timezone','UTC')) }}" class="mt-1 w-full rounded-xl border-slate-300"></div></div>
<div class="grid gap-4 md:grid-cols-3"><div><label class="font-medium">Registration deadline</label><input type="datetime-local" name="registration_deadline" value="{{ old('registration_deadline',isset($event)&&$event->registration_deadline?$event->registration_deadline->format('Y-m-d\TH:i'):'') }}" class="mt-1 w-full rounded-xl border-slate-300"></div><div><label class="font-medium">Registration mode</label><select name="registration_mode" class="mt-1 w-full rounded-xl border-slate-300">@foreach(['open','approval','invitation'] as $value)<option @selected(old('registration_mode',$event->registration_mode??'open')===$value)>{{ $value }}</option>@endforeach</select></div><div><label class="font-medium">Capacity</label><input type="number" name="capacity" min="1" max="100000" value="{{ old('capacity',$event->capacity??'') }}" class="mt-1 w-full rounded-xl border-slate-300"></div></div>
<div class="grid gap-4 md:grid-cols-2"><div><label class="font-medium">Physical location</label><input name="location" value="{{ old('location',$event->location??'') }}" class="mt-1 w-full rounded-xl border-slate-300"></div><div><label class="font-medium">Online meeting link</label><input type="url" name="online_url" value="{{ old('online_url',$event->online_url??'') }}" class="mt-1 w-full rounded-xl border-slate-300"></div></div>
<div class="grid gap-4 md:grid-cols-3"><div><label class="font-medium">Community ownership</label><select name="knowledge_community_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">No community</option>@foreach($communities as $community)<option value="{{ $community->id }}" @selected(old('knowledge_community_id',$event->knowledge_community_id??null)==$community->id)>{{ $community->name }}</option>@endforeach</select></div><div><label class="font-medium">Group ownership</label><select name="group_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">No group</option>@foreach($groups as $group)<option value="{{ $group->id }}" @selected(old('group_id',$event->group_id??null)==$group->id)>{{ $group->name }}</option>@endforeach</select></div><div><label class="font-medium">Category</label><select name="category_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">No category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id',$event->category_id??null)==$category->id)>{{ $category->name }}</option>@endforeach</select></div></div>
<div class="grid gap-4 md:grid-cols-2"><div><label class="font-medium">Co-organisers</label><select multiple name="co_organizer_ids[]" class="mt-1 h-40 w-full rounded-xl border-slate-300">@foreach($users as $user)<option value="{{ $user->id }}" @selected(in_array($user->id,old('co_organizer_ids',$editing?$event->coOrganizers->pluck('id')->all():[])))>{{ $user->full_name }}</option>@endforeach</select></div><div><label class="font-medium">Tags</label><select multiple name="tag_ids[]" class="mt-1 h-40 w-full rounded-xl border-slate-300">@foreach($tags as $tag)<option value="{{ $tag->id }}" @selected(in_array($tag->id,old('tag_ids',$editing?$event->tags->pluck('id')->all():[])))>{{ $tag->name }}</option>@endforeach</select></div></div>
<div class="grid gap-4 md:grid-cols-2"><div><label class="font-medium">Reminder minutes before event</label><div class="mt-2 flex flex-wrap gap-3">@foreach([10080=>'1 week',1440=>'1 day',60=>'1 hour',15=>'15 minutes'] as $minutes=>$label)<label class="flex items-center gap-2"><input type="checkbox" name="reminders[]" value="{{ $minutes }}" @checked(in_array($minutes,old('reminders',$editing?$event->reminders->pluck('minutes_before')->all():[1440,60])))>{{ $label }}</label>@endforeach</div></div><div class="space-y-2"><label class="flex items-center gap-2"><input type="checkbox" name="waitlist_enabled" value="1" @checked(old('waitlist_enabled',$event->waitlist_enabled??true))> Enable waitlist when full</label><label class="flex items-center gap-2"><input type="checkbox" name="certificate_enabled" value="1" @checked(old('certificate_enabled',$event->certificate_enabled??false))> Issue attendance certificates</label><label class="flex items-center gap-2"><input type="checkbox" name="requires_moderation" value="1" @checked(old('requires_moderation',$event->requires_moderation??false))> Require administrator moderation</label></div></div>
<div class="flex justify-end gap-3"><a href="{{ $editing?route('knowledge.events.show',$event):route('knowledge.events.index') }}" class="rounded-xl border px-5 py-3">Cancel</a><button class="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">{{ $editing?'Save event':'Create event' }}</button></div></form>
@endsection
