@extends('layouts.app')
@section('title','Academic Events')
@section('page-title','Academic Events')
@section('page-subtitle','Seminars, conferences, defenses, workshops, hackathons and training')
@section('content')
@include('knowledge._nav')
<div class="mb-6 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 class="text-2xl font-bold">Discover academic events</h1><p class="mt-1 text-slate-600">Register for public or institutional sessions, manage attendance, receive reminders, and earn verified certificates where enabled.</p></div>@auth @can('create',App\Models\AcademicEvent::class)<a href="{{ route('knowledge.events.create') }}" class="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Organise event</a>@endcan @endauth</div>
<form method="GET" class="mb-6 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-5"><input name="q" value="{{ $filters['q']??'' }}" placeholder="Search title or venue" class="rounded-xl border-slate-300 md:col-span-2"><select name="type" class="rounded-xl border-slate-300"><option value="">All types</option>@foreach(['seminar','conference','guest_lecture','research_presentation','project_defense','siwes_orientation','workshop','hackathon','competition','training'] as $type)<option value="{{ $type }}" @selected(($filters['type']??'')===$type)>{{ str($type)->headline() }}</option>@endforeach</select><select name="period" class="rounded-xl border-slate-300">@foreach(['upcoming','ongoing','past','mine'] as $period)<option value="{{ $period }}" @selected(($filters['period']??'upcoming')===$period)>{{ ucfirst($period) }}</option>@endforeach</select><button class="rounded-xl border border-blue-600 px-4 py-2 font-semibold text-blue-700">Filter</button></form>
<div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">@forelse($events as $event)<a class="rounded-2xl border bg-white p-5 shadow-sm hover:border-blue-300" href="{{ route('knowledge.events.show',$event) }}"><div class="flex justify-between"><span class="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-medium text-blue-700">{{ str($event->event_type)->headline() }}</span><span class="text-xs text-slate-500">{{ ucfirst($event->format) }}</span></div><h2 class="mt-4 text-xl font-bold">{{ $event->title }}</h2><p class="mt-2 text-sm text-slate-600">{{ $event->starts_at->timezone($event->timezone)->format('D, M j, Y · g:i A') }} {{ $event->timezone }}</p><p class="mt-1 text-sm text-slate-500">{{ $event->location ?: 'Online event' }}</p><p class="mt-4 text-xs text-slate-500">{{ $event->registrations_count }} attending{{ $event->capacity?' · '.$event->capacity.' capacity':'' }}</p></a>@empty<div class="rounded-2xl border border-dashed bg-white p-10 text-center md:col-span-3">No events match these filters.</div>@endforelse</div><div class="mt-6">{{ $events->links() }}</div>
@endsection
