@extends('layouts.app')
@section('title','Academic Events')
@section('page-title','Academic Events')
@section('page-subtitle','Seminars, conferences, defenses, workshops, hackathons and training')
@section('content')
@include('knowledge._nav')
<div class="space-y-7">
    <section class="rounded-[2rem] bg-gradient-to-br from-violet-950 via-slate-950 to-fuchsia-950 p-7 text-white shadow-xl sm:p-9"><div class="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p class="text-xs font-black uppercase tracking-[.24em] text-fuchsia-300">Academic calendar</p><h1 class="mt-2 text-3xl font-black sm:text-4xl">Events & opportunities</h1><p class="mt-3 max-w-3xl text-sm leading-7 text-slate-300">Discover academic sessions, register, receive reminders, track attendance and earn certificates where enabled.</p></div>@auth @can('create',App\Models\AcademicEvent::class)<a href="{{ route('knowledge.events.create') }}" class="rounded-xl bg-white px-5 py-3 text-sm font-black text-slate-950">Organise event</a>@endcan @endauth</div></section>
    <form method="GET" class="grid gap-3 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-5"><input name="q" value="{{ $filters['q']??'' }}" placeholder="Search title or venue…" class="rounded-xl border-slate-300 md:col-span-2"><select name="type" class="rounded-xl border-slate-300"><option value="">All types</option>@foreach(['seminar','conference','guest_lecture','research_presentation','project_defense','siwes_orientation','workshop','hackathon','competition','training'] as $type)<option value="{{ $type }}" @selected(($filters['type']??'')===$type)>{{ str($type)->headline() }}</option>@endforeach</select><select name="period" class="rounded-xl border-slate-300">@foreach(['upcoming','ongoing','past','mine'] as $period)<option value="{{ $period }}" @selected(($filters['period']??'upcoming')===$period)>{{ ucfirst($period) }}</option>@endforeach</select><button class="rounded-xl bg-slate-900 px-4 py-2 text-sm font-black text-white">Apply filters</button></form>
    <div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">@forelse($events as $event)<a href="{{ route('knowledge.events.show',$event) }}" class="group flex min-h-72 flex-col rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-violet-200 hover:shadow-xl"><div class="flex items-center justify-between"><span class="rounded-full bg-violet-50 px-3 py-1 text-xs font-bold text-violet-700">{{ str($event->event_type)->headline() }}</span><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{{ str($event->format)->headline() }}</span></div><p class="mt-5 text-xs font-black uppercase tracking-wide text-fuchsia-600">{{ $event->starts_at->timezone($event->timezone)->format('D · M j · g:i A') }}</p><h2 class="mt-2 text-xl font-black text-slate-900 group-hover:text-violet-700">{{ $event->title }}</h2><p class="mt-3 text-sm text-slate-500">{{ $event->location ?: 'Online event' }}</p><div class="mt-auto flex items-center justify-between border-t border-slate-100 pt-5"><span class="text-xs font-bold text-slate-500">{{ $event->registrations_count }} attending{{ $event->capacity?' / '.$event->capacity:'' }}</span><span class="text-sm font-black text-violet-600">View event →</span></div></a>@empty<div class="md:col-span-2 xl:col-span-3 rounded-[2rem] border border-dashed border-slate-300 bg-white p-14 text-center"><h2 class="text-xl font-black text-slate-900">No events match these filters</h2><p class="mt-2 text-sm text-slate-500">Try another event type or time period.</p></div>@endforelse</div>{{ $events->links() }}
</div>
@endsection
