@extends('layouts.app')
@php($editing=isset($community))
@section('title',$editing?'Edit Community':'Create Community')
@section('page-title',$editing?'Edit Community':'Create Community')
@section('page-subtitle','Define a clear purpose, membership model and moderation rules')
@section('content')
@include('knowledge._nav')
<form method="POST" enctype="multipart/form-data" action="{{ $editing?route('knowledge.communities.update',$community):route('knowledge.communities.store') }}" class="mx-auto max-w-4xl space-y-6 rounded-2xl border bg-white p-6">@csrf @if($editing)@method('PUT')@endif
<div><label class="font-medium">Community name</label><input name="name" required value="{{ old('name',$community->name??'') }}" class="mt-1 w-full rounded-xl border-slate-300"></div><div><label class="font-medium">Cover image</label><input type="file" name="cover_image" accept="image/jpeg,image/png,image/webp" class="mt-1 w-full rounded-xl border border-slate-300 p-2"><p class="mt-1 text-xs text-slate-500">JPG, PNG or WebP, up to 8 MB. The file is scanned before storage.</p></div>
<div><label class="font-medium">Purpose</label><textarea name="description" required rows="5" class="mt-1 w-full rounded-xl border-slate-300">{{ old('description',$community->description??'') }}</textarea></div>
<div class="grid gap-4 md:grid-cols-3"><div><label class="font-medium">Type</label><select name="community_type" class="mt-1 w-full rounded-xl border-slate-300">@foreach(['department','faculty','course','research_area','discipline','technology','professional_interest'] as $type)<option value="{{ $type }}" @selected(old('community_type',$community->community_type??'research_area')===$type)>{{ str($type)->headline() }}</option>@endforeach</select></div><div><label class="font-medium">Visibility</label><select name="visibility" class="mt-1 w-full rounded-xl border-slate-300">@foreach(['public','institution','private'] as $value)<option value="{{ $value }}" @selected(old('visibility',$community->visibility??'public')===$value)>{{ ucfirst($value) }}</option>@endforeach</select></div><div><label class="font-medium">Membership</label><select name="membership_mode" class="mt-1 w-full rounded-xl border-slate-300">@foreach(['open','approval','closed'] as $value)<option value="{{ $value }}" @selected(old('membership_mode',$community->membership_mode??'open')===$value)>{{ ucfirst($value) }}</option>@endforeach</select></div></div>
<div class="grid gap-4 md:grid-cols-2"><div><label class="font-medium">Category</label><select name="category_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">No category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id',$community->category_id??null)==$category->id)>{{ $category->name }}</option>@endforeach</select></div><div><label class="font-medium">Tags</label><select multiple name="tag_ids[]" class="mt-1 h-32 w-full rounded-xl border-slate-300">@foreach($tags as $tag)<option value="{{ $tag->id }}" @selected(in_array($tag->id,old('tag_ids',$editing?$community->tags->pluck('id')->all():[])))>{{ $tag->name }}</option>@endforeach</select></div></div>
<div><label class="font-medium">Community rules (one per line)</label><textarea name="rules_text" rows="5" class="mt-1 w-full rounded-xl border-slate-300">{{ old('rules_text',$editing?implode("\n",$community->rules??[]):'') }}</textarea></div>
<div class="flex flex-wrap gap-5"><label class="flex items-center gap-2"><input type="checkbox" name="requires_moderation" value="1" @checked(old('requires_moderation',$community->requires_moderation??false))> Review member posts before publishing</label><select name="status" class="rounded-xl border-slate-300"><option value="active">Active</option><option value="draft" @selected(($community->status??'')==='draft')>Draft</option>@if($editing)<option value="archived" @selected($community->status==='archived')>Archived</option>@endif</select></div>
<div class="flex justify-end gap-3"><a href="{{ $editing?route('knowledge.communities.show',$community):route('knowledge.communities.index') }}" class="rounded-xl border px-5 py-3">Cancel</a><button class="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">{{ $editing?'Save changes':'Create community' }}</button></div></form>
@endsection
