@extends('layouts.app')
@section('title','Academic Communities')
@section('page-title','Academic Communities')
@section('page-subtitle','Broad academic networks for knowledge, events and public collaboration')
@section('content')
@include('knowledge._nav')
<div class="mb-6 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 class="text-2xl font-bold">Discover communities</h1><p class="mt-1 text-slate-600">Communities are broad spaces around disciplines, institutions, courses, technologies and professional interests. Use Groups for smaller working teams.</p></div>@auth @can('create',App\Models\KnowledgeCommunity::class)<a href="{{ route('knowledge.communities.create') }}" class="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Create community</a>@endcan @endauth</div>
<form method="GET" class="mb-6 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-4"><input name="q" value="{{ $filters['q']??'' }}" placeholder="Search communities" class="rounded-xl border-slate-300 md:col-span-2"><select name="type" class="rounded-xl border-slate-300"><option value="">All purposes</option>@foreach(['department','faculty','course','research_area','discipline','technology','professional_interest'] as $type)<option value="{{ $type }}" @selected(($filters['type']??'')===$type)>{{ str($type)->headline() }}</option>@endforeach</select><button class="rounded-xl border border-blue-600 px-4 py-2 font-semibold text-blue-700">Search</button></form>
<div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">@forelse($communities as $community)<a class="rounded-2xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300" href="{{ route('knowledge.communities.show',$community) }}"><div class="flex justify-between gap-3"><span class="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-medium text-blue-700">{{ str($community->community_type)->headline() }}</span><span class="text-xs text-slate-500">{{ ucfirst($community->visibility) }}</span></div><h2 class="mt-4 text-xl font-bold">{{ $community->name }}</h2><p class="mt-2 line-clamp-3 text-sm text-slate-600">{{ $community->description }}</p><p class="mt-4 text-xs text-slate-500">{{ $community->members_count }} members · {{ $community->posts_count }} posts · {{ $community->membership_mode }} membership</p></a>@empty<div class="rounded-2xl border border-dashed bg-white p-10 text-center md:col-span-3">No communities match these filters.</div>@endforelse</div><div class="mt-6">{{ $communities->links() }}</div>
@endsection
