@extends('layouts.app')
@section('title','Academic Communities')
@section('page-title','Academic Communities')
@section('page-subtitle','Academic networks for knowledge, events and collaboration')
@section('content')
@include('knowledge._nav')
<div class="space-y-7">
    <section class="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-indigo-950 via-slate-950 to-cyan-950 p-7 text-white shadow-xl sm:p-9"><div class="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-cyan-400/15 blur-3xl"></div><div class="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div class="max-w-3xl"><p class="text-xs font-black uppercase tracking-[.24em] text-cyan-300">Academic network</p><h1 class="mt-2 text-3xl font-black sm:text-4xl">Discover communities</h1><p class="mt-3 text-sm leading-7 text-slate-300">Join broad spaces around disciplines, institutions, research areas and professional interests. For focused working teams, use Groups.</p></div>@auth @can('create',App\Models\KnowledgeCommunity::class)<a href="{{ route('knowledge.communities.create') }}" class="rounded-xl bg-white px-5 py-3 text-sm font-black text-slate-950 shadow">Create community</a>@endcan @endauth</div></section>
    <form method="GET" class="grid gap-3 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-4"><input name="q" value="{{ $filters['q']??'' }}" placeholder="Search communities…" class="rounded-xl border-slate-300 md:col-span-2"><select name="type" class="rounded-xl border-slate-300"><option value="">All purposes</option>@foreach(['department','faculty','course','research_area','discipline','technology','professional_interest'] as $type)<option value="{{ $type }}" @selected(($filters['type']??'')===$type)>{{ str($type)->headline() }}</option>@endforeach</select><button class="rounded-xl bg-slate-900 px-4 py-2 text-sm font-black text-white">Search</button></form>
    <div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">@forelse($communities as $community)<a href="{{ route('knowledge.communities.show',$community) }}" class="group flex min-h-64 flex-col overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:border-indigo-200 hover:shadow-xl"><div class="h-2 bg-gradient-to-r from-indigo-500 via-blue-500 to-cyan-400"></div><div class="flex flex-1 flex-col p-6"><div class="flex items-center justify-between gap-3"><span class="rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-700">{{ str($community->community_type)->headline() }}</span><span class="text-xs font-bold text-slate-400">{{ str($community->visibility)->headline() }}</span></div><h2 class="mt-5 text-xl font-black text-slate-900 group-hover:text-indigo-700">{{ $community->name }}</h2><p class="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{{ $community->description }}</p><div class="mt-auto grid grid-cols-3 gap-2 border-t border-slate-100 pt-5 text-center"><div><p class="font-black text-slate-900">{{ $community->members_count }}</p><p class="text-[10px] font-bold uppercase text-slate-400">Members</p></div><div><p class="font-black text-slate-900">{{ $community->posts_count }}</p><p class="text-[10px] font-bold uppercase text-slate-400">Posts</p></div><div><p class="text-xs font-black text-indigo-600">{{ str($community->membership_mode)->headline() }}</p><p class="text-[10px] font-bold uppercase text-slate-400">Access</p></div></div></div></a>@empty<div class="md:col-span-2 xl:col-span-3 rounded-[2rem] border border-dashed border-slate-300 bg-white p-14 text-center"><div class="text-4xl">🌐</div><h2 class="mt-4 text-xl font-black text-slate-900">No matching communities</h2><p class="mt-2 text-sm text-slate-500">Try another search or create a new academic community.</p></div>@endforelse</div>{{ $communities->links() }}
</div>
@endsection
