@extends('layouts.app')
@section('title', 'Discussion: '.$discussion->title)
@section('content')
<div class="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-8">
    <section class="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm sm:p-8">
        <a href="{{ route('discussions.index',$course) }}" class="text-sm font-bold text-indigo-600">← Back to discussions</a>
        <div class="mt-5 flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
            <div class="max-w-4xl"><div class="flex flex-wrap gap-2">@if($discussion->is_pinned)<span class="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">Pinned</span>@endif @if($discussion->status==='resolved')<span class="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-800">Resolved</span>@endif @if($discussion->priority==='high')<span class="rounded-full bg-rose-100 px-3 py-1 text-xs font-bold text-rose-700">High priority</span>@endif</div><h1 class="mt-3 text-3xl font-black tracking-tight text-slate-950">{{ $discussion->title }}</h1><p class="mt-2 text-sm text-slate-500">Started by <span class="font-bold text-slate-700">{{ $discussion->user->full_name }}</span> · {{ $discussion->created_at->format('M j, Y · H:i') }} @if($discussion->resolved_at)· resolved by {{ $discussion->resolver?->full_name }}@endif</p></div>
            <div class="flex flex-wrap gap-2">@can('update',$discussion)<a href="{{ route('discussions.edit',[$course,$discussion]) }}" class="rounded-xl border border-slate-200 px-4 py-2 text-sm font-bold text-slate-700">Edit</a>@endcan<form method="POST" action="{{ route('discussions.subscribe',[$course,$discussion]) }}">@csrf<button class="rounded-xl border border-slate-200 px-4 py-2 text-sm font-bold text-slate-700">Notifications</button></form>@if(auth()->user()->isLecturer()||auth()->user()->isAdmin())<form method="POST" action="{{ route('discussions.pin',[$course,$discussion]) }}">@csrf<button class="rounded-xl bg-amber-500 px-4 py-2 text-sm font-black text-white">{{ $discussion->is_pinned?'Unpin':'Pin' }}</button></form>@endif</div>
        </div>
        <div class="mt-7 whitespace-pre-line text-sm leading-8 text-slate-700">{{ $discussion->content }}</div>
        @if($discussion->tags->isNotEmpty())<div class="mt-5 flex flex-wrap gap-2">@foreach($discussion->tags as $tag)<span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{{ $tag->name }}</span>@endforeach</div>@endif
        @if($discussion->material)<a href="{{ route('materials.show',[$course,$discussion->material]) }}" class="mt-5 flex items-center justify-between rounded-2xl border border-indigo-100 bg-indigo-50 p-4 text-sm"><span><span class="font-black text-indigo-700">Related course material</span><br><span class="text-slate-700">{{ $discussion->material->title }}</span></span><span class="font-bold text-indigo-600">Open →</span></a>@endif
    </section>

    @include('ai._contextual-assistant', ['assistantFeature' => 'discussion_assistant', 'assistantEndpoint' => route('ai.context.discussion',[$course,$discussion])])

    <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7">
        <div class="flex items-center justify-between gap-3"><div><p class="text-xs font-black uppercase tracking-[.18em] text-indigo-600">Course conversation</p><h2 class="mt-1 text-xl font-black text-slate-900">Replies <span class="text-slate-400">({{ $replies->total() }})</span></h2></div></div>
        <div class="mt-5 space-y-4">
            @forelse($replies as $reply)
                <article class="rounded-2xl border {{ $reply->is_verified_response ? 'border-emerald-200 bg-emerald-50/40' : 'border-slate-200' }} p-5">
                    <div class="flex gap-4"><div class="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-slate-900 font-black text-white">{{ strtoupper(substr($reply->user?->first_name ?? $reply->user?->full_name ?? '?',0,1)) }}</div><div class="min-w-0 flex-1"><div class="flex flex-wrap items-start justify-between gap-2"><div><p class="font-black text-slate-900">{{ $reply->user?->full_name }}</p><p class="text-xs text-slate-400">{{ $reply->created_at->diffForHumans() }}</p></div>@if($reply->is_verified_response)<span class="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700">Accepted answer</span>@endif</div><p class="mt-3 whitespace-pre-line text-sm leading-7 text-slate-700">{{ $reply->body }}</p>
                    <div class="mt-4 flex flex-wrap items-center gap-2">@foreach(['helpful','insightful','agree'] as $reaction)<form method="POST" action="{{ route('discussions.replies.react',[$course,$discussion,$reply]) }}">@csrf<input type="hidden" name="reaction" value="{{ $reaction }}"><button class="rounded-lg border border-slate-200 px-2.5 py-1 text-xs font-bold text-slate-600 hover:bg-slate-50">{{ ucfirst($reaction) }}</button></form>@endforeach<span class="text-xs text-slate-400">{{ $reply->reactions_count }} reactions</span>@if($reply->comment_type==='answer'&&!$discussion->resolved_at&&(auth()->user()->isLecturer()||auth()->user()->isAdmin()))<form method="POST" action="{{ route('discussions.replies.accept',[$course,$discussion,$reply]) }}">@csrf<button class="rounded-lg bg-emerald-600 px-3 py-1 text-xs font-bold text-white">Accept answer</button></form>@endif</div>
                    @if($reply->replies->isNotEmpty())<div class="mt-4 space-y-3 border-l-2 border-indigo-100 pl-4">@foreach($reply->replies as $child)<div class="rounded-xl bg-slate-50 p-3"><p class="text-xs font-bold text-slate-800">{{ $child->user?->full_name }} · <span class="font-normal text-slate-400">{{ $child->created_at->diffForHumans() }}</span></p><p class="mt-1 text-sm text-slate-600">{{ $child->body }}</p></div>@endforeach</div>@endif
                    @if($discussion->status==='open')<details class="mt-4"><summary class="cursor-pointer text-xs font-bold text-indigo-600">Reply to this response</summary><form method="POST" action="{{ route('discussions.reply',[$course,$discussion]) }}" class="mt-3">@csrf<input type="hidden" name="parent_reply_id" value="{{ $reply->id }}"><input type="hidden" name="type" value="comment"><textarea required name="content" rows="2" class="w-full rounded-xl border-slate-300" placeholder="Write a nested reply"></textarea><button class="mt-2 rounded-xl bg-indigo-600 px-4 py-2 text-sm font-bold text-white">Post reply</button></form></details>@endif</div></div>
                </article>
            @empty<div class="rounded-2xl border border-dashed border-slate-300 p-10 text-center text-sm text-slate-500">No replies yet. Be the first to contribute.</div>@endforelse
        </div>
        <div class="mt-5">{{ $replies->links() }}</div>
        @if($discussion->status==='open'||auth()->user()->isAdmin())<div class="mt-7 rounded-2xl bg-slate-50 p-5"><h3 class="font-black text-slate-900">Add your response</h3><form method="POST" action="{{ route('discussions.reply',[$course,$discussion]) }}" class="mt-3">@csrf<textarea name="content" rows="4" required class="w-full rounded-xl border-slate-300" placeholder="Write a useful response. You can mention users where supported."></textarea><div class="mt-3 flex flex-wrap gap-2"><select name="type" class="rounded-xl border-slate-300"><option value="answer">Answer</option><option value="comment">Comment</option><option value="clarification">Clarification</option></select><button class="rounded-xl bg-slate-900 px-5 py-2 text-sm font-black text-white">Post response</button></div></form></div>@endif
    </section>

    <div class="flex justify-end"><details class="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm"><summary class="cursor-pointer font-bold text-rose-700">Report discussion</summary><form method="POST" action="{{ route('discussions.report',[$course,$discussion]) }}" class="mt-3 flex flex-wrap gap-2">@csrf<select name="reason" class="rounded-xl border-rose-200"><option value="spam">Spam</option><option value="harassment">Harassment</option><option value="academic_integrity">Academic integrity</option><option value="misinformation">Misinformation</option><option value="other">Other</option></select><input name="details" class="rounded-xl border-rose-200" placeholder="Optional details"><button class="rounded-xl bg-rose-600 px-4 py-2 font-bold text-white">Submit report</button></form></details></div>
</div>
@endsection
