@extends('layouts.app')
@section('title',$path->title)
@section('page-title',$path->title)
@section('page-subtitle',$path->creator?->full_name.' · '.$path->access_type)
@section('content')
@include('knowledge._nav')
@php($progress = $enrollment ? min(100,(float)$enrollment->progress) : 0)
<div class="space-y-6">
    <section class="rounded-[2rem] bg-gradient-to-br from-slate-950 via-indigo-950 to-violet-950 p-7 text-white shadow-xl sm:p-9"><div class="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div class="max-w-4xl"><div class="flex flex-wrap gap-2"><span class="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">{{ str($path->access_type)->headline() }}</span><span class="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">{{ str($path->visibility)->headline() }}</span><span class="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">{{ $path->items->count() }} steps</span></div><h1 class="mt-4 text-3xl font-black sm:text-4xl">{{ $path->title }}</h1><p class="mt-3 max-w-3xl text-sm leading-7 text-slate-300">{{ $path->description }}</p><p class="mt-3 text-xs text-indigo-200">Created by {{ $path->creator?->full_name ?? 'AcadFlow creator' }}</p></div><div class="shrink-0">@if($enrollment)<div class="min-w-60 rounded-2xl border border-white/10 bg-white/10 p-4 backdrop-blur"><div class="flex justify-between text-xs font-bold"><span>Your progress</span><span>{{ number_format($progress,0) }}%</span></div><div class="mt-2 h-2 overflow-hidden rounded-full bg-white/15"><div class="h-full rounded-full bg-violet-300" style="width:{{ $progress }}%"></div></div></div>@elseif(auth()->check()&&$hasAccess)<form method="POST" action="{{ route('knowledge.learning.enroll',$path) }}">@csrf<button class="rounded-xl bg-white px-5 py-3 text-sm font-black text-slate-950">Enroll in path</button></form>@elseif(auth()->check()&&$path->access_type==='premium')<form method="POST" action="{{ route('commerce.learning.purchase',$path) }}" class="flex flex-col gap-2 rounded-2xl bg-white/10 p-4">@csrf<select name="gateway" class="rounded-xl border-white/10 bg-white text-slate-900">@foreach($gateways as $gateway)<option value="{{ $gateway->code }}">{{ $gateway->name }}</option>@endforeach</select><button class="rounded-xl bg-amber-400 px-4 py-2 text-sm font-black text-slate-950">Purchase · NGN {{ number_format((float)$path->price,2) }}</button></form>@endif</div></div></section>

    @if(auth()->id()===$path->creator_id || auth()->user()?->isAdmin())
        <details class="rounded-3xl border border-slate-200 bg-white shadow-sm"><summary class="cursor-pointer list-none p-5 font-black text-slate-900">+ Add a step to this path</summary><form method="POST" action="{{ route('knowledge.learning.items.store',$path) }}" class="grid gap-3 border-t border-slate-100 p-5 md:grid-cols-2">@csrf<input required name="title" class="rounded-xl border-slate-300" placeholder="Item title"><select name="item_kind" class="rounded-xl border-slate-300"><option value="publication">Publication</option><option value="course_material">Course material</option><option value="assignment">Assignment</option><option value="quiz">Quiz</option><option value="external">External resource</option></select><input name="item_id" type="number" class="rounded-xl border-slate-300" placeholder="Existing item ID"><input name="url" class="rounded-xl border-slate-300" placeholder="External URL"><textarea name="description" rows="3" class="rounded-xl border-slate-300 md:col-span-2" placeholder="Description"></textarea><label class="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="is_required" value="1" checked> Required step</label><button class="rounded-xl bg-slate-900 px-4 py-2 text-sm font-black text-white">Add step</button></form></details>
    @endif

    <section><div class="flex items-end justify-between"><div><p class="text-xs font-black uppercase tracking-[.18em] text-indigo-600">Journey</p><h2 class="mt-1 text-2xl font-black text-slate-900">Path curriculum</h2></div></div><div class="mt-5 space-y-4">@forelse($path->items as $item)<article class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div class="flex gap-4"><div class="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-indigo-50 font-black text-indigo-700">{{ $item->position }}</div><div><h3 class="font-black text-slate-900">{{ $item->title }}</h3><p class="mt-1 text-sm leading-6 text-slate-500">{{ $item->description }}</p><p class="mt-2 text-xs font-bold text-slate-400">{{ $item->estimated_minutes }} min · {{ str($item->item_kind)->replace('_',' ')->headline() }}</p></div></div>@if($enrollment)<form method="POST" action="{{ route('knowledge.learning.progress',[$enrollment,$item]) }}" class="flex shrink-0 gap-2">@csrf @method('PATCH')<select name="status" class="rounded-xl border-slate-300 text-sm"><option>in_progress</option><option>completed</option><option>not_started</option></select><button class="rounded-xl bg-indigo-600 px-3 py-2 text-xs font-black text-white">Save</button></form>@endif</div></article>@empty<div class="rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center text-sm text-slate-500">This learning path does not have any steps yet.</div>@endforelse</div></section>
</div>
@endsection
