@extends('layouts.app')
@section('title',$path->title)
@section('page-title',$path->title)
@section('page-subtitle',$path->creator?->full_name.' · '.$path->access_type)
@section('content')
@include('knowledge._nav')
<div class="rounded-2xl border bg-white p-6"><p class="text-slate-600">{{ $path->description }}</p>@if($enrollment)<div class="mt-4"><div class="h-2 rounded bg-slate-100"><div class="h-2 rounded bg-blue-600" style="width:{{ min(100,(float)$enrollment->progress) }}%"></div></div><p class="mt-1 text-xs">{{ $enrollment->progress }}% complete</p></div>@elseif(auth()->check() && $hasAccess)<form class="mt-4" method="POST" action="{{ route('knowledge.learning.enroll',$path) }}">@csrf<button class="rounded-xl bg-blue-600 px-4 py-2 text-white">Enroll</button></form>@elseif(auth()->check() && $path->access_type==='premium')<form class="mt-4 flex gap-2" method="POST" action="{{ route('commerce.learning.purchase',$path) }}">@csrf<select name="gateway" class="rounded-xl border-slate-300">@foreach($gateways as $gateway)<option value="{{ $gateway->code }}">{{ $gateway->name }}</option>@endforeach</select><button class="rounded-xl bg-amber-700 px-4 py-2 text-white">Purchase NGN {{ number_format((float)$path->price,2) }}</button></form>@endif</div>
@if(auth()->id()===$path->creator_id || auth()->user()?->isAdmin())<form method="POST" action="{{ route('knowledge.learning.items.store',$path) }}" class="mt-6 grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-2">@csrf<input required name="title" class="rounded-xl border-slate-300" placeholder="Item title"><select name="item_kind" class="rounded-xl border-slate-300"><option value="publication">Publication</option><option value="course_material">Course material</option><option value="assignment">Assignment</option><option value="quiz">Quiz</option><option value="external">External resource</option></select><input name="item_id" type="number" class="rounded-xl border-slate-300" placeholder="Existing item ID"><input name="url" class="rounded-xl border-slate-300" placeholder="External URL"><textarea name="description" class="rounded-xl border-slate-300 md:col-span-2" placeholder="Description"></textarea><label><input type="checkbox" name="is_required" value="1" checked> Required</label><button class="rounded-xl border px-4 py-2">Add item</button></form>@endif
<div class="mt-6 space-y-3">@foreach($path->items as $item)<div class="rounded-2xl border bg-white p-5"><div class="flex justify-between"><strong>{{ $item->position }}. {{ $item->title }}</strong><span class="text-xs">{{ $item->estimated_minutes }} min</span></div><p class="mt-2 text-sm text-slate-500">{{ $item->description }}</p>@if($enrollment)<form method="POST" action="{{ route('knowledge.learning.progress',[$enrollment,$item]) }}" class="mt-3 flex gap-2">@csrf @method('PATCH')<select name="status" class="rounded-xl border-slate-300"><option>in_progress</option><option>completed</option><option>not_started</option></select><button class="rounded-xl border px-3">Save progress</button></form>@endif</div>@endforeach</div>
@endsection
