@extends('layouts.app')
@section('title','Create Collaboration Group')
@section('content')
<div class="mx-auto max-w-3xl px-4 py-8">
    <div class="mb-6"><a href="{{ route('groups.index') }}" class="text-sm text-blue-700">← Back to groups</a><h1 class="mt-2 text-3xl font-bold">Create a collaboration group</h1><p class="mt-2 text-slate-600">Institutional links are optional, so independent users can create professional or research groups.</p></div>
    <form method="POST" enctype="multipart/form-data" action="{{ route('groups.store') }}" class="space-y-6 rounded-2xl border bg-white p-6 shadow-sm">@csrf
        <div><label class="font-medium">Group name</label><input name="name" value="{{ old('name') }}" required maxlength="255" class="mt-1 w-full rounded-xl border-slate-300">@error('name')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label class="font-medium">Cover image</label><input type="file" name="cover_image" accept="image/jpeg,image/png,image/webp" class="mt-1 w-full rounded-xl border border-slate-300 p-2"></div>
        <div><label class="font-medium">Purpose and description</label><textarea name="description" rows="5" class="mt-1 w-full rounded-xl border-slate-300">{{ old('description') }}</textarea></div>
        <div class="grid gap-4 md:grid-cols-3"><div><label class="font-medium">Group type</label><select name="group_type" required class="mt-1 w-full rounded-xl border-slate-300">@foreach(['study','research','project','departmental','professional','course','siwes','seminar'] as $type)<option value="{{ $type }}" @selected(old('group_type')===$type)>{{ str($type)->headline() }}</option>@endforeach</select></div><div><label class="font-medium">Visibility</label><select name="visibility" class="mt-1 w-full rounded-xl border-slate-300">@foreach(['private','institution','public'] as $value)<option value="{{ $value }}">{{ ucfirst($value) }}</option>@endforeach</select></div><div><label class="font-medium">Joining</label><select name="membership_mode" class="mt-1 w-full rounded-xl border-slate-300">@foreach(['approval','open','invitation'] as $value)<option value="{{ $value }}">{{ ucfirst($value) }}</option>@endforeach</select></div></div>
        <div><label class="font-medium">Maximum members</label><input type="number" name="max_members" value="{{ old('max_members',10) }}" min="2" max="250" class="mt-1 w-full rounded-xl border-slate-300"></div>
        <div class="grid gap-4 md:grid-cols-3"><div><label class="font-medium">Course (optional)</label><select name="course_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">No course</option>@foreach($courses as $course)<option value="{{ $course->id }}">{{ $course->code }} — {{ $course->name }}</option>@endforeach</select></div><div><label class="font-medium">Community (optional)</label><select name="knowledge_community_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">No community</option>@foreach($communities as $community)<option value="{{ $community->id }}">{{ $community->name }}</option>@endforeach</select></div><div><label class="font-medium">Research project (optional)</label><select name="research_project_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">No project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->title }}</option>@endforeach</select></div></div>
        <div class="flex justify-end gap-3"><a href="{{ route('groups.index') }}" class="rounded-xl border px-5 py-3">Cancel</a><button class="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Create group</button></div>
    </form>
</div>
@endsection
