@extends('layouts.app')
@section('title','Collaboration Groups')
@section('content')
<div class="mx-auto max-w-7xl space-y-7 px-4 py-8 sm:px-6 lg:px-8">
    <section class="rounded-[2rem] bg-gradient-to-br from-blue-950 via-slate-950 to-cyan-950 p-7 text-white shadow-xl sm:p-9"><div class="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div class="max-w-3xl"><p class="text-xs font-black uppercase tracking-[.24em] text-cyan-300">Focused collaboration</p><h1 class="mt-2 text-3xl font-black sm:text-4xl">Groups</h1><p class="mt-3 text-sm leading-7 text-slate-300">Build smaller study, research, project, SIWES, seminar or professional teams with members, tasks, files and working discussions.</p></div>@can('create',App\Models\Group::class)<a href="{{ route('groups.create') }}" class="rounded-xl bg-white px-5 py-3 text-sm font-black text-slate-950">Create group</a>@endcan</div></section>
    <form method="GET" class="grid gap-3 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-4"><input name="q" value="{{ $filters['q']??'' }}" placeholder="Search groups…" class="rounded-xl border-slate-300 md:col-span-2"><select name="type" class="rounded-xl border-slate-300"><option value="">All types</option>@foreach(['study','research','project','departmental','professional','course','siwes','seminar'] as $type)<option value="{{ $type }}" @selected(($filters['type']??'')===$type)>{{ str($type)->headline() }}</option>@endforeach</select><button class="rounded-xl bg-slate-900 px-4 py-2 text-sm font-black text-white">Filter</button></form>
    <div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">@forelse($groups as $group)<a href="{{ route('groups.show',$group) }}" class="group flex min-h-64 flex-col rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl"><div class="flex items-center justify-between"><span class="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{{ str($group->group_type)->headline() }}</span><span class="text-xs font-bold text-slate-400">{{ str($group->visibility)->headline() }}</span></div><h2 class="mt-5 text-xl font-black text-slate-900 group-hover:text-blue-700">{{ $group->name }}</h2><p class="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{{ $group->description ?: 'A focused collaboration group.' }}</p><div class="mt-auto grid grid-cols-2 gap-3 border-t border-slate-100 pt-5"><div><p class="text-[10px] font-black uppercase text-slate-400">Members</p><p class="mt-1 font-black text-slate-900">{{ $group->active_members_count }}/{{ $group->max_members }}</p></div><div class="text-right"><p class="text-[10px] font-black uppercase text-slate-400">Leader</p><p class="mt-1 truncate text-sm font-bold text-slate-700">{{ $group->leader->full_name }}</p></div></div>@if($group->course)<p class="mt-3 rounded-xl bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-500">{{ $group->course->code }} · {{ $group->course->name }}</p>@endif</a>@empty<div class="md:col-span-2 xl:col-span-3 rounded-[2rem] border border-dashed border-slate-300 bg-white p-14 text-center"><div class="text-4xl">🤝</div><h2 class="mt-4 text-xl font-black text-slate-900">No matching groups</h2><p class="mt-2 text-sm text-slate-500">Create a focused collaboration space or broaden your filters.</p></div>@endforelse</div>{{ $groups->links() }}
</div>
@endsection
